

Activate_spring_brake=彈簧式停留軔機緊軔
Activate_spring_break=彈簧式停留軔機緊軔
Headlamp_Switch_4=調車
Headlamp_Switch_LCZ=調車標誌（CZ）
Headlamp_Switch_Traxx_1=列車尾端標誌
Headlamp_Switch_Pc1_dim=列車前端標誌（減光）
Radio=無線電
Radio_Zew1=ZEW 1
Radio_Turn_on=開啟無線電
Camera=攝影機
Camera_Cabin=駕駛室攝影機
Camera_Orbiting=環繞攝影機
Camera_Outside=車外攝影機
Camera_next_in_vehicle=下一個車內攝影機
Confirm=確認
Release_emergency_brake=解除緊急制軔
Release_emergency_break=解除緊急制軔
Enable_emergency_brake=施加緊急制軔
Enable_emergency_break=施加緊急制軔
Activate_cabin=啟用駕駛室
Deactivate_Cab=停用駕駛室
Activate_main_switch=投入主斷路器
Active_Cab_Single_Traction=啟用駕駛室（單機運轉）
Activation_Of_The_Last_Cabin_In_Multiple_Traction=啟用重聯列車最後端駕駛室
Activation_Of_The_First_Cabin_In_Multiple_Driving=啟用重聯列車最前端駕駛室
Pantograph=集電弓
Pantograph_Raise_Back=升起後集電弓
Pantograph_Lower_Back=降下後集電弓
Pantograph_Lower_Front=降下前集電弓
Pantograph_Raise_Front=升起前集電弓
Lights=燈光
Light_pos_A=A
Light_pos_M=M
Train/Lights/Light_pos_M=M
Light_pos_L=L
Light_pos_JW=JW
Light_disabled=關閉
Lights_Short=近光燈
Lights_long=遠光燈
Instrument_lighting=儀表照明
Turn_on_lights=開啟燈光
Turn_off_lights=關閉燈光
Lights_Signal=標誌燈
Lights_Dim=標誌燈減光
Wipers=雨刷
Wipers_0=0
Wipers_1=1
Wipers_2=2
Wipers_3=3
Wipers_4=4
Doors_open_right=開啟右側車門
Drive_direction_backward=後退
Drive_direction_neutral=中立位
Drive_direction_forward=前進
Release_spring_brake=彈簧式停留軔機鬆軔
Release_spring_break=彈簧式停留軔機鬆軔
Turn_on_lights_level_2=開啟照明（第 2 段）
Turn_on_lights_level_3=開啟照明（第 3 段）
Lights_turn_off_engine_room_lights=關閉機械室照明
Lights_turn_on_engine_room_lights=開啟機械室照明
Lights_desk=控制桌照明
Turn_off_desk_lights=關閉控制桌照明
Battery=蓄電池
Turn_on_battery=投入蓄電池
Turn_on_batttery=投入蓄電池
Turn_off_battery=切離蓄電池
Interior_Lights_0=關閉車內照明
Interior_Lights_1=車內照明減光
Toggle=切換
Toggle_cruise_control=切換定速控制
Cruise_control_0=<kmph>0</kmph>
Washer=擋風玻璃洗滌器
Cruise_control_deactivate=停用定速控制
Cruise_control=定速控制
Cruise_control_40=<kmph>40</kmph>
Cruise_control_50=<kmph>50</kmph>
Cruise_control_60=<kmph>60</kmph>
Cruise_control_70=<kmph>70</kmph>
Cruise_control_80=<kmph>80</kmph>
Cruise_control_120=<kmph>120</kmph>
Cruise_control_140=<kmph>140</kmph>
Cruise_control_160=<kmph>160</kmph>
Headlamp_Switch_0=關閉
Headlamp_Switch_1=一般行車
Headlamp_Switch_2=左線行車
Headlamp_Switch_3=單機行車
Headlamp_Switch_5=警報號誌
Headlamp_Switch_Pc6=路線中停車標誌
Doors_open_both=開啟兩側車門
Radio_Zew3=ZEW 3
Radio_Turn_off=關閉無線電
Radio_Previous_Channel=上一個頻道
Radio_Next_Channel=下一個頻道
Radio_Set_Channel=設定頻道
Radio_Set_Channel_1=頻道 1
Radio_Set_Channel_2=頻道 2
Radio_Set_Channel_3=頻道 3
Radio_Set_Channel_4=頻道 4
Radio_Set_Channel_5=頻道 5
Radio_Set_Channel_6=頻道 6
Radio_Set_Channel_7=頻道 7
Radio_Set_Channel_8=頻道 8（緊急）
Radio_Set_Channel_9=頻道 9（調車）


Train=列車控制
Camera_previous_in_vehicle=上一個車內攝影機
Camera_reverse_camera=後視攝影機
Cabin_activation=駕駛室啟用
Light_pos_JN=JN
Doors=車門
Doors_open_left=開啟左側車門
Doors_close=關閉車門
Drive_direction=行駛方向
Lights_cabin=駕駛室照明
Turn_on_lights_level_1=開啟照明（第 1 段）
Engine_room=機械室
Turn_on_desk_lights=開啟控制桌照明
Interior_Lights_2=車內照明全亮
Cruise_control_activate=啟用定速控制
Cruise_control_100=<kmph>100</kmph>
Brakes=軔機
Breaks=軔機
Camera_Outpost=號誌站內部
Turn_on_flashlight=開啟手電筒
Turn_off_flashlight=關閉手電筒
Radio_Set_Channel_10=頻道 10（Radiostop 測試）
Cruise_control_20=<kmph>20</kmph>
Cruise_control_90=<kmph>90</kmph>
Cruise_control_110=<kmph>110</kmph>
Cruise_control_10=<kmph>10</kmph>
Cruise_control_30=<kmph>30</kmph>
