



Katowice_Zawodzie_Description=[KZ] 卡托维兹-扎沃杰站有两个站台，仅有通勤列车停靠。两条独立的线路承接 1 号铁路线和 138 号铁路线的运输业务。
Bedzin_Description=[Bn] 本津站位于栋布罗瓦-古尔尼恰与索斯诺维茨总站之间，共有6条主要股道，其中仅有3条为电气化，仅有通勤列车停靠。
Dabrowa_Gornicza_Description=[DG] 栋布罗瓦-古尔尼恰站仅有一个岛式站台，承接长途列车和区域列车的客运业务。
Lazy_Lc_Description=[ŁC] 瓦济 C 信号楼是一个连接瓦济站的信号楼，信号楼可控制道岔，将货物列车从 宗布科维采、普热米亚尔基引向瓦济站的货运区，所有客运列车通过。
Gora_Wlodowska_Description=[GW] 伏沃多维采乡 古拉站是一个在中央铁路干线上没有站台的会让站，两条侧线用于列车待避。
Psary_Description=[Ps] 普萨雷站是从中央铁路干线分岔出支线、通往科兹武夫 - 科涅茨波尔 64 号铁路线的车站。该车站有三条正线和两条侧线，站内无站台。
Knapwowka_Description=[Kn] 克纳普夫卡站是一个位于中央铁路干线上的线路所，由此可以通往恰恩察站。
Wloszczowa_Polnoc_Description=[WP] 伏沃晓瓦北站是中央铁路干线上中型站，有两个站台。三条轨道用于承接长途客运列车的停靠业务，由此可以通往‌热利斯瓦维采。
Olszamowice_Description=[Ol]（LCS）奥尔沙莫维采站是中央铁路干线上一个有两条侧线的小站。本站还远程控制临近的皮利霍维采线路所。
Opoczno_Poludnie_Description=[OP] 奥波奇诺南站是中央铁路干线上仅有一个站台的车站，部分长途列车停靠。
Dabrowa_Gornicza_Wschodnia_Description=[DW] 栋布罗瓦-古尔尼恰东站是 62 号铁路线和 171 号铁路线的交会站，有一个站台供通勤列车停靠，货运列车大多通过本站。
Zawiercie_Description=[Zw] 扎维尔切站是一个拥有两个站台、多条侧线的大站，货运列车及大多数客运列车在此停靠。CMK（中央铁路干线 / 4 号铁路线）在此结束，从华沙方向驶来的列车继续在 1 号铁路线上运行。
Sosnowiec_Glowny_Description=[SG] 索斯诺维茨总站是波兰 18 个最高等级站之一，所有客运列车均在此停靠。1 号铁路线与 62 号铁路线在本站交汇，去往 62 号铁路线的列车停靠本站南侧的索斯诺维茨南站。
Pilichowice_Description=[Pl] 皮利霍维采站是中央铁路干线上一个只负责左右侧行车转换的线路所。
Sosnowiec_Poludniowy_Description=[SPł] 索斯诺维茨南站是一个小型枢纽站，从索斯诺维茨-丹杜夫卡驶来的单线在此一分为二，均通往索斯诺维茨总站。其中一条线路接入站内，另一条从南侧绕行车站。这里共有七条轨道，其中两条具备客运乘降能力。车站旁还设有一个多式联运的集装箱枢纽。
Idzikowice_Description=[Id] 伊季科维采站是中央铁路干线上最大的车站，两条支线分别通向马佐夫舍省 托马舒夫 - 拉多姆线路的两个方向。车站内有一个客运车厢修理厂，以及地区铁路运营商的机车车辆维修点。本站没有站台。
Slawkow_Description=[Sł] 斯瓦夫库夫站是一个位于栋布罗瓦-古尔尼恰东和布科夫诺中间的中等车站。共有四条电气化轨道，其中两条共用一个站台，有区域列车停靠。
Dorota_Description=[Dra] 多罗塔站是一条复线铁路和一条单线铁路交汇的线路所。
Grodzisk_Mazowiecki_Description=[Gr] 马佐夫舍省 格罗济斯克站位于华沙郊区，区域列车、长途列车、国际列车均在此处停靠。本站一共有两个站台，也有越行线。这是CMK（中央铁路干线 / 4 号铁路线）的起点。
Kozlow_Description=[Kz] 科兹武夫站是一个主要供区域列车停靠的中等大小的车站。站内共有三个站台，不过也有部分非区域列车会直接越行。这里是前往科涅茨波尔、普萨雷、森济舒夫、卡托维兹、克拉科夫等方向的重要枢纽站。
Tunel_Description=[Tl] 隧道村站是一个分线小站，从华沙方向开来的列车可以从这里去往克拉科夫或者索斯诺维茨。站内仅有一个站台，供部分区域列车停靠。
Korytow_Description=[Kr] 克里图夫站是 CMK 上的第一个车站，除了四条主要使用的股道外，还有许多侧线用于装载，本站没有站台。
LazyLA_Description=[ŁA] 瓦济 A 信号楼是一个靠近瓦济站的信号楼，负责从货场将列车送至扎维尔切方向，所有客运列车通过。
LazyLB_Descritpion=[ŁB] 瓦济 B 信号楼负责控制瓦济 B 区域，同时也管理瓦济整备场。
Juliusz_Description=[Ju] 尤利乌什站是一个小线路所，拥有一个通往附近企业的支线。由此可以将列车送入左侧轨道运行，或使列车恢复右侧运行。
Szeligi_Description=[Se] 谢利基站是一个位于CMK上的小站，连接开往马库夫的支线。
Katowice_Description=[KO] 卡托维兹站是上西里西亚地区最大的枢纽站，也是波兰 18 个特等站之一。共有五个站台，区域列车、长途列车和国际列车均在此停靠。
Dabrowa_Gornicza_Zabkowice_Description=[DZ] 栋布罗瓦-古尔尼恰 宗布科维采站是栋布罗瓦-古尔尼恰地区的一个枢纽站，可通往卡托维兹市中心、瓦济和卡托维兹钢铁厂方向。本站有三个站台和多条侧线。
DGHK_Description=[DGHK] 栋布罗瓦-古尔尼恰 卡托维兹钢铁厂站是栋布罗瓦-古尔尼恰 宗布科维采、栋布罗瓦-古尔尼恰南和栋布罗瓦-古尔尼恰 斯特热梅希采之间的枢纽站，也服务于钢铁厂支线。
Bukowno_Description=[Bo] 布科夫诺站位于斯瓦夫库夫和奥尔库什之间，有十条股道，其中四条可为两个站台提供服务。只有通勤列车在此停靠。
Lazy_Description=[ŁB] 瓦济 B 信号楼位于瓦济 A 和瓦济 C 之间，负责控制站台所在的车站中央部分。
Pruszkow_Description=[Pr]（LCS）普鲁什库夫站是华沙城郊的一个中型车站。该站唯一的站台只供各停列车和区域列车停靠。车站内有几条侧线和一个集装箱装卸区。在此可远程控制约瑟芬努夫线路所，在那里进行客货分离。
SosnowiecKazimierz_Description=[SKz] 索斯诺维茨-卡齐米日站是一个小型枢纽站，连接着索斯诺维茨-丹杜夫卡、索斯诺维茨-马奇基和栋布罗瓦-古尔尼恰 斯特热梅希采这三条单线线路。本站有三个站台，只供通勤列车停靠。
Strzalki_Description=[St]（LCS）斯特扎乌基站是 CMK 上一个有两条侧线的小站。在此可远程控制临近的白拉夫斯卡线路所。
KrakowPrzedmiescie_Description=[KPm] 克拉科夫 郊区站是一个掌控进入克拉科夫方向的小型线路所。货运列车在此与客运列车分离，客运列车由此进入市中心的中央车站。
Slomniki_Description=[Sm] 斯沃姆尼基站是一个位于梅胡夫和熊村之间的小站，只有通勤列车在此停靠。共有四条股道，其中三条可办理客运业务。
Raciborowice_Description=[Rc] 拉契波罗维采站是一个小线路所，负责将克拉科夫钢铁厂和克拉科夫-巴托维采方向的列车进行分离与汇合。 
KrakowBatowice_Description=[Bt] 克拉科夫-巴托维采站是一个拥有六条股道的中等大小的车站。其中三条设有站台的股道供区域列车等客车停靠。
Miechow_Descrption=[Mi] 梅胡夫站是一个位于隧道村和斯沃姆尼基之间的小站，有四条股道，可用于供慢速列车待避。车站有两条股道位于站台旁，通勤列车和一些速度较慢的长途列车在此停靠。
Starzyny_Description=[Str] （LCS）斯塔日内线路所是从中央铁路干线前往科兹沃夫时的第一站。列车可以从这里转线到 CMK 前往华沙，或者向西经由科涅茨波尔前往琴斯托霍瓦。在此可远程控制临近的斯普罗瓦线路所。
Zastow_Description=[Zs] 扎斯图夫站是一个位于拉契波罗维采线路所和熊村之间的小站。有两条侧线可供慢车待避，另外两条设有站台的股道只供通勤列车停靠。
Niedzwiedz_Description=[Nd] 熊村站是一个小型车站，有两条股道可用于慢车待避，另外两条设有站台的股道只供通勤列车停靠。
Zyrardow_Description=[Żr]（LCS）日拉尔杜夫站是位于马佐夫舍省 格罗济斯克和斯凯尔涅维采之间的车站。本站有两个站台，可同时容纳三列客车。本站的信号楼还控制着附近的马佐夫舍省 拉季维武夫线路所。
Plycwia_description=[Pł] 普维契维亚站是一座位于斯凯尔涅维采和罗古夫之间的小型车站。本站有两个站台，还有两条可用于待避的侧线。
Rogow_description=[Rg] 罗古夫站是一座位于科卢什基站和普维契维亚站之间的中型车站。这里只有一个岛式站台，位于两条正线之间，另外还有四条侧线，如有需要可供列车待避。
Koluszki_description=[Kl] 科卢什基站是一座大型枢纽站，通往罗兹的线路从连接华沙和卡托维兹的线路中分离出来。这里有三个站台和许多可用于待避的侧线。
Galkowek_description=[G]（LCS）加乌库维克站是科卢什基附近的一座小车站，为两条线路提供服务：一条通往罗兹工业区站的客运线路（17 号铁路线）和一条经由罗兹-奥莱胡夫货运站的货运线路（25 号铁路线）。在客运线路旁设有两个站台。本站信号楼还远程控制着位于罗兹-维泽夫附近的罗兹-安杰尤夫站。
Zakowice_Description=[ŻPd] （LCS）扎科维采南站是罗兹至科卢什基绕行线路上的一个线路所，主要供货运列车通行。本站调度岗位位于科卢什基站信号楼，同时远程控制临近的斯沃特维内站。
Skierniewice_description=[Ske] 斯凯尔涅维采站是一座大型枢纽站，通往华沙、罗兹、沃维奇和武库夫的线路在这里交汇。除了三个站台，本站还有很多侧线可供技术停车的列车使用。车站旁边有一座历史悠久的蒸汽机车车库。
Widzew_Description=[ŁW] （LCS）罗兹-维泽夫站是位于罗兹地区的一座重要车站，途经本市的各等级客运列车均在本站停靠。本站还有一个当地运输公司的维修基地。客运列车总共可以使用三个站台和六条轨道。货运列车可以通过使用避让线完全避开车站正线。该站还远程控制着临近的罗兹-栋布罗瓦线路所，以及罗兹-马里辛站。
Wlochy_description=[Wł] 华沙-弗沃赫是一座负责调度从西侧驶入华沙的客运列车的线路所。卡托维兹、波兹南及马佐夫舍省 格罗济斯克方向的线路在此交汇。
Rokiciny_Description=[Rk] 罗基齐内站位于彼得库夫-特雷布纳尔斯基站与科卢什基站之间。该站配有一个装载货场，它还拥有不同寻常的站台布置：它位于进站信号与出站信号之间。
Baby_Description=[B] 巴贝站位于彼得库夫-特雷布纳尔斯基站与科卢什基站之间。除去一条侧线与一个装载货场外，它还拥有不同寻常的站台布置：它位于进站信号与出站信号之间。
Pabianice_Description=[Pc] 帕比亚尼采站配有一座岛式站台，以及一座侧式站台。去往瓦斯克站的线路配备有自动闭塞所。
Gajewniki_Description=[Gw] 加耶夫尼基站是位于兹敦斯卡沃拉附近的枢纽线路所。从该站分出多条线路通往连接南北的煤炭运输干线。
Lask_Description=[Łs] 瓦斯克站配有一座岛式站台，以及一座侧式站台。它还拥有一条去往军事基地的专用线。去往帕比亚尼采站和加耶夫尼基站的线路配备有自动闭塞所。
Zabieniec_Description=[ŁŻ] 罗兹-扎别涅茨站是位于兹盖日站与罗兹-卡里斯卡站之间的中型车站。该站配有两座侧式站台，以及若干侧线。
Zgierz_Description=[Zg] 兹盖日站是一座枢纽车站，负责引导来自沃维奇和库特诺方向的列车前往罗兹-维泽夫站和罗兹-卡里斯卡站。车站内设有波兰国家铁路能源公司的专用线。
Lublinek_Description=[ŁLb] 罗兹-卢布利内克站位于罗兹-卢布利内克机场附近。该站配有两座岛式站台，仅供区域列车停靠。
Retkinia_Description=[Rt] 莱特基尼亚站是一个负责引导从兹敦斯卡沃拉方向的列车，去往兹盖日站或是科卢什基站方向的线路所。在罗兹-卢布利内克方向的线路处，建有罗兹-莱特基尼亚乘降所。
Zdunska_Wola_Description=[ZW] 兹敦斯卡沃拉站是一座大型枢纽车站，多条线路由此分支延伸至煤炭运输干线。车站设有两座站台及多条用于货运的附加轨道。区域列车及部分长途列车停靠本站。
Chojny_Description=[ŁCh] 罗兹-霍伊内站位于罗兹地区南部，长期以来不承担客运业务，年久失修。随着罗兹工业区站的重建，该站开始承担长途列车与区域列车的客运业务。车站配有两个站台。
Kaliska_Description=[ŁK] 罗兹-卡里斯卡站是位于罗兹市西部的一座大型枢纽车站。该站承担着来自库特诺、沃维奇、兹敦斯卡沃拉和罗兹-霍伊内方向的列车运输任务。车站设有三个站台及多条用于列车运行的轨道。
Witonia_Description=[Wt] （LCS）维托尼亚站是位于兹盖日至库特诺单线铁路上的车站。它还远程控制文奇察站和奥佐尔库夫站。两个车站都有装卸场，与此同时文奇察站还有军用侧线。每个车站都有用于客运乘降的站台。
Zgierz_Polnoc_Description=[ZgP] （LCS）兹盖日北站的调度岗位位于兹盖日站信号楼，同时远程控制兹盖日 - 库特诺单线铁路上的三个车站。兹盖日 孔特勒维斯站和兹盖日北站各有两条股道和两座较短的侧式站台。霍齐谢夫站则有两座较长的站台和一条额外的股道。
Glinnik_Description=[Gl] （LCS）格林尼克站是一座配备了继电器联锁系统的会让站。本站还远程控制斯特勒库夫站，该站有一条额外的正线和一个装卸场。
Glowno_Description=[Gn]（LCS）格沃夫诺站于2015年进行了现代化改造，在此期间安装了计算机联锁设备。现代化之后，格沃夫诺站的调度员也远程控制多玛涅维采站。多玛涅维采站用于测试一种新型信号，其信号机主体装置可以降低高度。
Lowicz_Przedmiescie_Description=[ŁP] 沃维奇郊区站是 15 号线单线铁路上的一个中型车站。除了 15 号线继续向贝德纳雷‌站方向延伸外，本站还有两条连接沃维奇总站的线路。
Lowicz_Glowny_Description=[ŁG] 沃维奇总站是位于 E20 干线上的大型枢纽站。CE20 货运走廊在这里分叉，允许货运列车绕过华沙铁路枢纽，途经斯凯尔涅维采，然后驶向武库夫方向。车站有两个岛式站台。在现代化过程中，曾经的阿卡迪亚和普拉琴察‌线路所被并入车站。
Belchow_Description=[Bł] 贝乌胡夫站是位于斯凯尔涅维采和沃维奇总站之间唯一的车站。车站有一座站台和五条股道。其调度岗位于斯凯尔涅维采站信号楼。通往斯凯尔涅维采站的线路配备了在现代化过程中安装的自动闭塞信号系统。
