


#means information for the neighboring station that the train runs on the left track on a double track line (in Poland it normally runs on the right)
Incorrect_dep=向非正常行車線發車

#means switching on the devices associated with the neighboring station, making it possible to obtain permission from the dispatcher of the neighboring station to leave a train
Lock_activation=啟用閉塞裝置

#means turning on / off the semaphores informing the driver about the correct operation of the journey
Turn_crossing_signal=切換平交道防護號誌

#allows our station area to be controlled remotely by another station
Auth_2_ctrl_area=授予區域控制權

#cancellation of the permission to control our station area remotely by another station
Cancel_auth_4_area=收回區域控制權

#removal of the warning label
Delete_sign=移除標示牌

#Means the immediate cancellation of the prepared journey path for the train - initiation of the command
Immieddiate_route_cancel=立即解鎖列車進路 - 初始化

#axle counter reset in case of its failure - track occupancy device - confirmation
Reset_axle_counter_conf=計軸器歸零 - 確認

#means changing the direction of a line block in order to obtain permission to run a train
Choose_interlock_dir=設定閉塞方向

#means resignation from activating the line block
Cancel_turn_on_interlock=取消設定閉塞方向

#emergency change of the line blockade direction - confirmation
Emer_interlock_dir_change_conf=緊急變更閉塞方向 - 確認

#resetting the occupancy of several sections of the automatic line block on the route between stations, maintaining the distance between trains going in the same direction - initialization
Reset_automat_block_signal_init=復歸多個自動閉塞分區 - 初始化

#potwierdzenie wyjazdu pociągu na szlak w kierunku sąsiedniej stacji
Block_dep_block=鎖閉始端閉塞單元

#RBC is the Radio Block Center, part of the ETCS European Train Control System for communication between the control room, semaphores and the driver's cab
Rbc_data_sync=更新 RBC 資料
Set_sim_speed=設定模擬速度
Stop_train_traffic=暫停列車運轉

#Set the ALARM (ALARM is a radio signal that automatically stops all nearby trains radio range)
Set_alarm=向行車控制站附近所有列車發送無線電 ALARM 警報訊號
Signal_sam=啟用號誌自動控制
SendOrder_ExecuteOrder=送出
EbiLabelDropdown_2=股道封鎖
EbiLabelDropdown_9=注意！轉轍器維修中。
MultiplayerIntroduction_Driver_WelcomeDriver=歡迎來到 SimRail 多人遊戲。這是您第一次在多人遊戲中擔任司機員。
MultiplayerIntroduction_Driver_AFK=若長時間沒有操作，AI 會自動接管列車。
MultiplayerIntroduction_Driver_Remember=請記得您正與其他玩家協同運轉，並確實遵守號誌顯示與速限。
MultiplayerIntroduction_Driver_RadioChannel1=附近玩家必須與您使用相同的無線電頻道，才能收到您的訊息。從 AI 手中接管列車時，系統會自動設定為該路線使用的頻道。
MultiplayerIntroduction_Dispatcher_Comm=您可透過電話與鄰站聯絡。若鄰站由 AI 控制，電話上會顯示相關提示。
MultiplayerIntroduction_Dispatcher_AI=鄰站由 AI 控制時，通訊會使用清單中的預設文字訊息；若由其他玩家控制，則可使用其他通訊方式。
#type of train(cargo/passenger),place(station,place(station)
Your_task_to_drive_from_to=本次您將駕駛{0}列車，由{1}站行駛至{2}站。

#train number, place(station)
Report_2_station={0}，{1}。

#place(station), number of train
Station_2_train_radio_check={1}，{0}呼叫，無線電測試。

#number of train, place(station)
Report_2_station2={0}，{1}。

#place(station), number of train
Report_2_train={0}，{1}。

#place(station), number of train
Report_2_train_2={0}，{1}。
Reporting=收到，請講。

#number of train
Train_dep={0}，請開車。

#number of train
Train_rdy_2_dep={0}，列車準備完畢。

#number of train, number
Further_ride_on_L_no={0}，後續改行左側{1}股。

#number
Entrance_on_subst_on_line_no=因設備故障，將依代用號誌進入{0}股。

#number
Exit_on_subst_on_line_no=因設備故障，將依代用號誌由{0}股出站。

#number of train
To_brake={0} 緊軔。

#number of train
To_unbrake={0} 鬆軔。

#number of train
Brakes_good={0} 軔機正常。

#number of train
To_me={0} 向我來。

#number of train
From_me={0} 遠離我。

#number of train
Now_stop={0} 阿卡。

#number of train
Now_change_cabin={0} 現在換端。
Park_brake=停留軔機
Brake_on=緊軔
Brake_off=鬆軔
Etcs_confirm=ETCS 確認

#means giving permission for a train to depart from a neighboring station
Give_permission=核准發車

#means switching on the devices associated with the neighboring station, making it possible to obtain permission from the dispatcher of the neighboring station to leave a train
turn_on_block_sys=啟用閉塞裝置

#means that the train dispatcher has changed his mind and does not want to ask for permission to leave the train anymore
Turn_off_block_sys=取消啟用閉塞裝置

#means resetting the display of the enabling signal on the semaphore and resolving the prepared train path
Break_route=取消列車進路

#prepares the route for the train and displays the signal on the semaphore for the train
Setup_route=設定列車進路

#means requesting permission to leave the train from an adjacent station
Request_for_consent=請求發車許可

#means giving permission for a train to depart from a neighboring station
To_give_consent=核發發車許可

#gives a "green" light on a semaphore for a train
Lightup_allowance_lights=顯示允許號誌
Second_switch_button=轉轍器第二按鈕

#means confirmation for the neighboring station of the train's arrival on the left track on the double track line (in Poland it is normal to drive on the right)
Incorrect_arrival=由非正常行車線到達

#revokes permission for a neighboring station to send the train
Opt_out_from_consent=取消核發發車許可

#canceling the consent obtained earlier for the train to run (e.g. in a situation where the train will not run, e.g. because it broke down)
Consent_return=退還發車許可

#blocks the possibility of sending several trains within one consent for a line block - a separate consent is required for each train
Rotation_interlocking=逐列車許可
Departure=出發
Arrival=到達

#means consenting to the departure of the train from a neighboring station
Consent=發車許可

#means a change of direction in which the line block allows the train to depart (from station B to station A, instead of from station A to B)
Change_direction_of_blockade=變更閉塞方向

#means the confirmation that the train enters the station, thus clearing the line between stations and restoring the line block to its basic state
Lock_release=釋放閉塞

#means the change of direction in which the line block allows the train to run in an emergency
Emergency_change_direction_of_blockade=緊急變更閉塞方向
Stop=停止
Substitute_signal=代用號誌

#preparation of the travel path for the train
Route=列車進路

#preparation of the route for the fistula (maneuver)
Maneuver_route=調車進路

#confirms that the dispatcher has read the information about the train passing through the switch contrary to the direction in which it was set
Cancell_running_through_switch=確認擠岔警報

#this is a comand to "ignore the the fact that this railway line is occupied"
Ignore_occupation=略過區段占用

#means the bell informing that the train has passed through the switch contrary to the direction in which it was set
Point_failure_sig=擠岔警報

#turns off the power supply to the crossover control, etc., in order not to switch anything by mistake
Turn_off_dev_pwr=切斷轉轍控制電源

#means that the train has been set on the trail for a substitute signal (normally the starting block works automatically)
Emergency_dep_block=臨時辦理始端閉塞

#means that the train has entered the station on a substitute signal (normally the end block works automatically)
Emergency_arrival_block=臨時辦理終端閉塞

#line blockade power supply device
Interlock_convert=閉塞電源變流器

#emergency closing of the automatic passage
Emergency_close_crossing=緊急關閉自動平交道

#emergency opening of the automatic passage
Emergency_open_crossing=緊急開放自動平交道

#emergency closure of the passage for cars for a longer period of time
Car_traffic_close=關閉平交道

#resumption of car traffic through the crossing
Car_traffic_open=開放平交道
Emergency_close_crossing_2=緊急關閉平交道

#solution of the path set for the train in order to open the passage in an emergency (e.g. during an ambulance passage)
Route_cancel_4_crossing_open=取消進路並緊急開放平交道

#emergency cancellation of permission to control our station area remotely by another station - command initialization
Emerg_cancel_auth_4_area=緊急收回區域控制權 - 初始化

#emergency cancellation of permission to control our station area remotely by another station - command confirmation
Emerg_cancel_auth_4_are_conf=緊急收回區域控制權 - 確認

#emergency cancellation of permission to control our station area remotely by another station - command canceling
Cancel_special_command=取消特殊命令初始化

#means putting a warning plate on the desktop, reminding, for example, about the ongoing renovation works on a given track
insert_sign=新增標示牌

#preparation of the travel path for the train
Set_up_train_route=設定列車進路

#preparation of the route for the fistula (maneuver)
Set_up_shunting_route=設定調車進路

#means the cancellation of a prepared travel route
Route_cancel=解鎖進路

#means the immediate cancellation of the prepared journey path for the train - confirmation of the order
Immieddiate_route_cancel_confirm=立即解鎖列車進路 - 確認

#shifting the derailment (rolling stock derailing device, secures the passage of other trains against accidental entry) to the + position
Switch_derail_plus=脫軌器定位

#shifting the derailment to position -
Switch_derail_minus=脫軌器反位

#closure of a track section - exclusion from traffic (it is not possible to specify the route for a train through a given track)
Close_track_2=個別封鎖區段

#opening of a track section after temporary closure
Open_track=解除區段封鎖

#ignores the information about the occupancy of the switch, which would normally prevent it from being moved
Ignore_point_occupy=旁路轉轍器區段占用

#blocking the derailment in its current position
Derail_pos_lock=鎖定脫軌器終端位置

#disabling derailment blockade
Cancel_derailment_lock=解除脫軌器終端鎖定

#Moves the switch to the plus position, ignoring the information that it is occupied by a train
Switch_pos_plus_ignore_occupy=旁路占用並轉至定位

#It moves the switch to the minus position, ignoring the information that it is occupied by a train
Switch_pos_minus_ignore_occupy=旁路占用並轉至反位

#confirms that the dispatcher has read the information about the train passing through the switch contrary to the direction in which it was set
Confirm__point_failure_init=清除擠岔警報 - 初始化

#confirms that the dispatcher has read the information about the train passing through the switch contrary to the direction in which it was set
Confirm__point_failure_conf=清除擠岔警報 - 確認

#locks the derailleur in the plus position
Derailment_pos_lock_plus=手動鎖定脫軌器定位

#locks the derailleur in the minus position
Derailment_pos_lock_minus=手動鎖定脫軌器反位

#disabling derailment blockade
Cancel_derailment_pos_lock=解除脫軌器手動鎖定
Switch_point_to_plus_pos=轉轍器定位
Switch_point_to_minus_pos=轉轍器反位
Switch_point_to plus_pos=轉轍器定位
Switch_point_to minus_pos=轉轍器反位

#locks the translation of the turnout in its end position
Point_lock_in_end_pos=鎖定轉轍器終端位置

#cancels the interlock of the switch of the switch in its end position
Cancel_point_lock_end_pos=解除轉轍器終端鎖定

#axle counter reset in case of its failure - track occupancy device - initialization
Reset_axle_counter_init=計軸器歸零 - 初始化
Cancel_special_command2=取消特殊命令初始化
Close_track=個別封鎖股道
Open_track_2=解除股道封鎖

#blocks the possibility of displaying the signal on all semaphores in the station
Lock_all_semaphores=鎖定所有號誌機

#unlocks the ability to display the signal on all semaphores in the station
Unlock_all_semaphores=解除所有號誌機鎖定

#blocks the possibility of relocating all switches in the station
Lock_all_points=鎖定所有轉轍器

#unlocks the ability to relocate all switches in the station
Unlock_all_points=解除所有轉轍器鎖定

#cancellation of the substitute signal display
Subs_signal_cancel=取消代用號誌

#refreshing the status of all devices on the desktop
Refresh_all_obj=更新所有設備狀態
Point_lock_plus=手動鎖定轉轍器定位
Point_lock_minus=手動鎖定轉轍器反位
Cancel_point_lock=解除轉轍器手動鎖定

#means consent to change the direction of the linear blockade
Permission_4_dir_change=核准設定閉塞方向

#releases the set direction of the line lock
Release_interlock_dir=解除既定閉塞方向

#prevents the train from leaving the station in the selected direction
Lock_dep_in_dir=封鎖該方向出發

#enables the train to leave the station in the selected direction
Unlock_dep_in_dir=解除該方向出發封鎖

#emergency change of linear blockade direction - initialization
Emer_interlock_dir_change_init=緊急變更閉塞方向 - 初始化

#means changing the direction of a line block in order to obtain permission to run a train
Interlock_dir_change=變更閉塞方向

#oznacza danie zgody na zmianę kierunku działania blokady liniowej
Per_interlock_dir_change=核准變更閉塞方向

#releases the set direction of the line lock
Release_interlck_dir=取消變更閉塞方向

#resetting the occupancy of several sections of the automatic line block on the route between stations, maintaining the distance between trains going in the same direction - confirmation
Reset_automat_block_signal_conf=復歸多個自動閉塞分區 - 確認
Perm_to_reset_auto_block_init=核准復歸多個自動閉塞分區 - 初始化
Perm_to_reset_auto_block_conf=核准復歸多個自動閉塞分區 - 確認

#information about the train leaving for a linear block in the case of running for a substitute signal or a written order - initialization
Dep_ver_init=臨時確認列車出發至站間 - 初始化

#information about the train leaving for a linear block in the case of running on a substitute signal or a written order - confirmation
Dep_ver_conf=臨時確認列車出發至站間 - 確認

#ustawia trasę przejazdu dla podania sygnału zastępczego - inicjalizacja
Prep_route_for_subst_sig_init=準備以代用號誌或行車命令辦理進站 - 初始化

#ustawia trasę przejazdu dla podania sygnału zastępczego - potwierdzenie
Prep_route_for_subst_sig_conf=準備以代用號誌或行車命令辦理進站 - 確認
Give_permission_to=核准設定閉塞方向
Ack_train_arrival=確認列車到達
Permission_interlcok_dir_change=核准設定到達方向閉塞
Release_interlocking_init=臨時解除閉塞 - 初始化
Release_interlocking_conf=臨時解除閉塞 - 確認
Prep_2_takeover_right_2_area=準備接管區域控制權
Take_over_rights_2_area=接管區域控制權
Emergency_take_rights_area=緊急接管區域控制權
Confirm_rcb_launch=確認 RBC 啟動
Disconnect_rcb=中斷 RBC 連線
Restart_active_rcb_computer=重新啟動使用中的 RBC 電腦
Stop_sim=暫停模擬時間
Ressume_train_traffic=恢復列車運轉

#Cancel the ALARM (ALARM is a radio signal that automatically stops all nearby trains radio range)
Cancel_alarm=取消無線電 ALARM 警報訊號
















Signal_lock=號誌機鎖定於險阻顯示
Signal_unlock=解除號誌機險阻鎖定
Signal_sz=代用號誌 - 初始化
Signal_szp=代用號誌 - 確認
Signal_nsz=逆線發車代用號誌 - 初始化
Signal_nszp=逆線發車代用號誌 - 確認
Signal_saw=停用號誌自動控制
OrderReceived=命令已收到
OrderRejected=無法執行
OrderExecuted=命令已接受
ConfirmSpecialOrder=確認特殊命令
EbiLabelDropdown_1=股道占用
EbiLabelDropdown_3=單線雙向行車
EbiLabelDropdown_4=禁止電力車輛進入
EbiLabelDropdown_5=輔助車輛
EbiLabelDropdown_6=電話行車預告
EbiLabelDropdown_7=電話命令與回報
EbiLabelDropdown_8=已將發車通知施工負責人
MultiplayerIntroduction_Driver_ExpressTrain=今天您將駕駛特快列車。
MultiplayerIntroduction_Driver_FastTrain=今天您將駕駛快速列車。
MultiplayerIntroduction_Driver_AI=列車目前由 AI 控制。準備就緒後，您可隨時按下畫面上方的按鈕接管列車。
MultiplayerIntroduction_Driver_Comm=您可使用無線電語音（預設按鍵為波浪號鍵）或畫面左側的文字聊天與其他玩家通訊。
MultiplayerIntroduction_Driver_RadioChannel2=通過標有 R 與數字的指示牌後，請切換至數字所示的無線電頻道。您也可在設定中啟用自動切換頻道。
MultiplayerIntroduction_Driver_PlayersList=按 Tab 開啟玩家清單，即可確認您正接近的車站由玩家或 AI 管理；也可在此檢舉蓄意妨礙遊戲或長時間未操作的玩家。
MultiplayerIntroduction_Dispatcher_Welcome=歡迎來到 SimRail 多人遊戲。這是您第一次在多人遊戲中擔任行車調度員。
MultiplayerIntroduction_Dispatcher_Systems=您可使用三套基本系統：聯鎖控制盤、時刻表與通訊設備。
MultiplayerIntroduction_Dispatcher_Human=鄰站由玩家控制時，您可選用預設訊息、在與該鄰站的聊天視窗中輸入文字，或使用語音通話。
MultiplayerIntroduction_Dispatcher_Voice=若要使用語音通話，請拿起電話話筒，再按下欲呼叫車站的按鈕。
MultiplayerIntroduction_Dispatcher_IncommingCall=有人來電時，拿起話筒即可接聽。
MultiplayerIntroduction_Dispatcher_Radio=另一種通訊方式是無線電。您可透過左側聊天視窗或語音（預設按鍵為波浪號鍵），與附近的司機員通聯。
MultiplayerIntroduction_Dispatcher_RadioChannel=只有位於附近，且無線電與您的行車控制站使用相同頻道的玩家，才能聽見您的通聯。
MultiplayerIntroduction_Dispatcher_Playerslist=按 Tab 開啟玩家清單，即可查看附近玩家；也可在此檢舉蓄意妨礙遊戲或長時間未操作的玩家。
MultiplayerIntroduction_Dispatcher_Timetable1=時刻表螢幕可供您查看正在接近本站的列車。
MultiplayerIntroduction_Dispatcher_Timetable2=您可從中確認列車是否停靠本站、誤點多久、從哪個方向進站，以及應往哪個方向開出。
MultiplayerIntroduction_Dispatcher_MultipleStations=部分車站還負責遠端控制其他行車控制站，例如 Sosnowiec Główny 控制 Sosnowiec R52。若要查看後者的時刻表，請切換螢幕上的分頁。
MultiplayerIntroduction_Dispatcher_NearbyTrains=畫面左側會顯示附近列車，以及列車與最近號誌機的距離和該號誌機名稱。名稱開頭為車站縮寫，後段則是號誌機的專屬代號。
MultiplayerIntroduction_Dispatcher_Computer=您可使用電腦聯鎖介面或 EP 盤（積木式聯鎖控制盤）控制行車控制站。詳細操作說明位於「i」圖示，請先閱讀。
MultiplayerIntroduction_Dispatcher_LineBlocks=兩站之間可能採用自動閉塞或半自動閉塞。
MultiplayerIntroduction_Dispatcher_AutomaticLB=採自動閉塞時，無須向鄰站請求發車許可，只須將列車發車情形通知鄰站行車調度員。
MultiplayerIntroduction_Dispatcher_OthersLB=其他閉塞方式下，列車發車前須先以電話向鄰站請求許可，再操作控制盤辦理閉塞。
MultiplayerIntroduction_GL=祝您好運！
DominoPanel_DNSwitch_DayLabel=日間
DominoPanel_DNSwitch_NightLabel=夜間
Train_rdy={0}，請開車
train_on_collision_course=玩家 {0} 將 {1} 次列車送上會與 {2} 次列車相撞的進路
keyboard=鍵盤
disconnect_all=全部掛斷
suspend_call=保留通話
tape_recorder=錄音機
automatic_answering=自動接聽
