

map_border_reached=Dorazili jste k hranici mapy. Dále bude vlak řídit umělá inteligence.
train_derailed=Vlak {0} vykolejil! Dojde k odstranění.
train_missrouted=Postavená cesta od návěstidla {0} by poslala vlak {1} nesprávným směrem. Cesta byla zrušena!
train_missrouted_remove=Vlak {0} bude smazán, protože byl vypraven nesprávným směrem. Vlak se nachází ve stanici, která není uvedena v jízdním řádu.
trains_head-on_remove=Vlak {0} bude odstraněn z důvodu zjištění vzájemné blokace vlaků: {1}.
force_enabled_bot=Bot byl aktivován administrátorem.
AllowToPassSignal_allowed_to_pass=Vlak {0} dostal povolení projet návěstidlo {1} řízené hráčem {2}.
AllowToPassSignal_signal_not_at_danger=Vlak {0} se nachází před návěstidlem {1}, které nezakazuje jízdu.
AllowToPassSignal_train_not_at_controlled_signal=Vlak {0} je před návěstidlem {1}. Toto návěstidlo je řízeno někým jiným.
AllowToPassSignal_allowed_to_pass_canceled=Oprávnění k projetí návěstidla {1} řízeného hráčem {2} pro vlak {0} bylo zrušeno.
AllowToPassSignal_train_is_moving=Vlak {0} je právě v pohybu. Vlak musí nejdříve zastavit, abys mu mohl udělit oprávnění k projetí stůj.
AllowToPassSignal_no_trains_found=U řízených návěstidel nebyly nalezeny žádné vlaky.
AllowToPassSignal_etcs_l2=Použij funkci "Override EoA" v ETCS DMI. Zastav před nejbližším návěstidlem a použij tlačítko Start pro vyžádání oprávnění k jízdě (MA).
AllowToPassSignal_etcs_l1=Použij funkci "Override EoA" v ETCS DMI. Oprávnění k jízdě (MA) získáš u následující balízy.
