

map_border_reached=Das Ende der Karte wurde erreicht, somit übernimmt der Bot das Fahren des Zuges.
train_derailed=Zug {0} ist entgleist und wird damit gelöscht.
train_missrouted=Das Stellen der Fahrstraße von Signal {0} würde den Zug {1} in die falsche Richtung leiten. Die Fahrstraße wird aufgelöst!
train_missrouted_remove=Zug {0} wird gelöscht, da er in die falsche Richtung gesendet wurde. Der Zug ist aktuell in einem Bahnhof, welcher nicht im Fahrplan vorhanden ist.
trains_head-on_remove=Zug {0} wird wegen gegenseitiger Blockierung von folgenden Zügen gelöscht: {1}.
force_enabled_bot=Der Bot wurde durch einen Administrator aktiviert.
AllowToPassSignal_allowed_to_pass=Zug {0} hat vom Fahrdienstleiter {2} die Zustimmung erhalten, am haltzeigenden Signal {1} vorbeizufahren.
AllowToPassSignal_allowed_to_pass_canceled=Die Zustimmung für Zug {0} zur Vorbeifahrt am Signal {1} gesteuert vom Fahrdienstleiter {2} wurde widerrufen.
AllowToPassSignal_signal_not_at_danger=Zug {0} steht vor fahrtzeigendem Signal {1}. Eine Zustimmung zur Vorbeifahrt am haltzeigenden Signal ist nicht nötig.
AllowToPassSignal_etcs_l2=Nutze "Override EoA" im ETCS DMI. Halte vor dem nächsten Signal und nutze dann "Start", um eine neue MA (Fahrberechtigung) anzufordern.
AllowToPassSignal_etcs_l1=Nutze "Override EoA" im ETCS DMI. Du wirst am nächsten Signal eine neue MA (Fahrberechtigung) bekommen.
AllowToPassSignal_no_trains_found=Keine Züge vor gesteuerten Signalen gefunden.
AllowToPassSignal_train_not_at_controlled_signal=Zug {0} steht vor Signal {1}. Dieses wird von einem anderen Fahrdienstleiter gesteuert.
AllowToPassSignal_train_is_moving=Zug {0} ist in Bewegung. Er muss anhalten, damit der Vorbeifahrt am Signal zugestimmt werden kann.
