map_border_reached=You have reached the border of the map. Further, the bot will drive the train.
train_derailed=Train {0} has derailed! It will be removed.
train_missrouted=The set route from signal {0} would send train {1} in the wrong direction. Route will be released!
train_missrouted_remove=Train {0} will be deleted because it was sent in the wrong direction. The train is at a station that is not in the timetable.
trains_head-on_remove=Train {0} will be deleted due to mutual blocking of trains: {1}.
force_enabled_bot=The bot has been activated by an administrator.
AllowToPassSignal_allowed_to_pass=Train {0} received permission to pass signal {1} controlled by {2}.
AllowToPassSignal_allowed_to_pass_canceled=Permission to pass signal {1} controlled by {2} received by train {0} has been canceled.
AllowToPassSignal_signal_not_at_danger=Train {0} is in front of signal {1} that does not prohibit driving.
AllowToPassSignal_train_is_moving=Train {0} is moving. It has to be stopped in order to receive permission to pass signal.
AllowToPassSignal_train_not_at_controlled_signal=Train {0} is in front of signal {1}. This signal is controlled by someone else.
AllowToPassSignal_no_trains_found=No trains were found in front of the controlled signals.
AllowToPassSignal_etcs_l2=Use override EoA function in ETCS DMI. Stop in front of next signal and use Start button to request MA.
AllowToPassSignal_etcs_l1=Use override EoA function in ETCS DMI. You will get new MA at next signal balise.
