map_border_reached=Vous avez atteint le bord de la carte. L'IA va prendre le contrôle du train.
train_derailed=Le train {0} a déraillé ! Il va être supprimé.
train_missrouted=L'itinéraire depuis le signal {0} conduirait le train {1} dans la mauvaise direction. Cet itinéraire va donc être détruit !
train_missrouted_remove=Le train {0} va être supprimé car il a été envoyé dans la mauvaise direction. Il se trouve dans une gare qui n'est pas dans son horaire.
trains_head-on_remove=Le train {0} sera supprimé en raison d'un blocage mutuel des trains : {1}.
force_enabled_bot=Le bot a été activé par un administrateur.
AllowToPassSignal_allowed_to_pass=Le train {0} a reçu l'autorisation de franchir le signal {1} commandé par {2}.
AllowToPassSignal_no_trains_found=Aucun train n'a été détecté devant les signaux de contrôle.
AllowToPassSignal_allowed_to_pass_canceled=L'autorisation de franchir le signal {1}, commandé par {2} et reçu par le train {0}, a été annulée.
AllowToPassSignal_etcs_l2=Utilisez la fonction franchir EoA dans le DMI de l'ETCS. Arrêtez-vous devant le prochain signal et appuyez sur le bouton « Début » pour demander l'autorisation de marche (MA).
AllowToPassSignal_signal_not_at_danger=Le train {0} se trouve devant le signal {1}, qui lui permet de circuler.
AllowToPassSignal_train_is_moving=Le train {0} est en marche. Il doit être arrêté pour pouvoir recevoir l'autorisation de franchir le signal.
AllowToPassSignal_train_not_at_controlled_signal=Le train {0} se trouve devant le signal {1}. Celui-ci est commandé par un autre aiguilleur.
AllowToPassSignal_etcs_l1=Utilisez la fonction franchir EoA dans le DMI de l'ETCS. Vous obtiendrez une nouvelle MA à la prochaine balise de signalisation.
