map_border_reached=Dojechałeś do granicy mapy. Dalej pociąg poprowadzi bot.
train_derailed=Pociąg {0} wykoleił się! Pociąg zostanie usunięty.
train_missrouted=Nastawiony przebieg z semafora {0} wysłałby pociąg {1} w złym kierunku. Rozwiązywanie przebiegu!
train_missrouted_remove=Pociąg {0} zostanie usunięty ze względu na niepoprawne wyprawienie pociągu. Pociąg znajduje się na stacji, której nie ma w rozkładzie jazdy.
trains_head-on_remove=Pociąg {0} zostanie usunięty ze względu na blokowanie się wzajemne pociągów: {1}.
force_enabled_bot=Bot został aktywowany przez administratora.
AllowToPassSignal_allowed_to_pass=Pociąg {0} otrzymał zgodę na pominięcie semafora {1} sterowanego przez {2}.
AllowToPassSignal_allowed_to_pass_canceled=Zgoda na pominięcie semafora {1} sterowanego przez {2} dla pociągu {0} została cofnięta.
AllowToPassSignal_signal_not_at_danger=Pociąg {0} znajduje się przed semaforem {1}, który nie zabrania jazdy.
AllowToPassSignal_train_is_moving=Pociąg {0} się porusza. Musi on być zatrzymany, aby otrzymać zgodę na pominięcie semafora.
AllowToPassSignal_train_not_at_controlled_signal=Pociąg {0} znajduje się przed semaforem {1}. Semafor ten kontrolowany jest przez kogoś innego.
AllowToPassSignal_no_trains_found=Nie zaleziono pociągów przed kontrolowanymi semaforami.
AllowToPassSignal_etcs_l2=Użyj funkcji pomin EoA w interfejsie ETCS. Zatrzymaj się przed następnym semaforem i użyj guzika Start, aby zarządać MA.
AllowToPassSignal_etcs_l1=Użyj funkcji pomin EoA w interfejsie ETCS. Otrzymasz nowe MA przy nastęnym semaforze.
