

train_derailed={0} 次因脱轨将被从服务器上删除。
train_missrouted_remove={0} 次因运行方向错误将被从服务器上删除。
map_border_reached=您已达到可游玩区域边界，接下来该车将由 AI 接管。
train_missrouted=从信号机 {0} 开通的进路会导致 {1} 次运行方向错误。 进路已取消！
trains_head-on_remove=由于 {1} 次之间产生敌对进路，{0} 次将被从服务器上删除。
force_enabled_bot=管理员已强制启动 AI 驾驶。
AllowToPassSignal_allowed_to_pass={0} 次列车收到了来自调度员 {2} 的允许通过信号机 {1} 的许可。
AllowToPassSignal_train_not_at_controlled_signal={0} 次列车正在由其它玩家控制的信号机 {1} 前。
AllowToPassSignal_no_trains_found=在该受控信号机前没有发现列车。
AllowToPassSignal_etcs_l1=在ETCS 人机交互界面中选择“越行”功能。你会在下一信号机应答器处得到更新的移动授权。
AllowToPassSignal_allowed_to_pass_canceled={0} 次列车收到的来自调度员 {2} 的允许通过信号机 {1} 的许可已被取消。
AllowToPassSignal_signal_not_at_danger={0} 次列车正位于不会阻止列车通过的信号机 {1} 前。
AllowToPassSignal_train_is_moving={0} 次列车正在行驶，它必须停车才能获得通过信号的许可。
AllowToPassSignal_etcs_l2=在ETCS 人机交互界面中选择“越行”功能。在下一信号机前停车，并按下“启动”按键以申请移动授权。
