

train_derailed=列車 {0} 已出軌！該列車將被移除。
train_missrouted_remove=列車 {0} 因被發往錯誤方向而將被移除。該列車目前位於其時刻表未列出的車站。
map_border_reached=您已抵達地圖邊界。接下來將由 AI 駕駛列車。
train_missrouted=從號誌機 {0} 設定的進路會使列車 {1} 駛往錯誤方向。進路將予以解鎖！
trains_head-on_remove=列車 {0} 因與下列列車互相阻塞而將被移除：{1}。
force_enabled_bot=管理員已啟用 AI 駕駛。
AllowToPassSignal_allowed_to_pass=列車 {0} 已獲准通過由 {2} 控制的號誌機 {1}。
AllowToPassSignal_train_not_at_controlled_signal=列車 {0} 位於號誌機 {1} 前方，但該號誌機由其他人控制。
AllowToPassSignal_no_trains_found=受控號誌機前方未發現任何列車。
AllowToPassSignal_etcs_l1=請在 ETCS DMI 使用「越過 EoA」功能。您將在下一座號誌機的地上感應子處取得新的 MA。
AllowToPassSignal_allowed_to_pass_canceled=列車 {0} 通過由 {2} 控制之號誌機 {1} 的許可已撤銷。
AllowToPassSignal_signal_not_at_danger=列車 {0} 位於號誌機 {1} 前方，但該號誌機並未顯示險阻號誌。
AllowToPassSignal_train_is_moving=列車 {0} 正在移動。列車必須先停車，才能取得通過號誌機的許可。
AllowToPassSignal_etcs_l2=請在 ETCS DMI 使用「越過 EoA」功能。在下一座號誌機前停車，並按下「Start」按鈕申請 MA。
