

full_date=Zobrazit celé datum:
train_number_filter=Číslo vlaku:
# Description
post=Stanice:
time_enter_modal_error_arrival_time_greater_actual=Proběhl pokus o zadání pozdějšího času příjezdu, než je aktuální čas.
time_enter_modal_error_departure_time_greater_actual=Byl učiněn pokus o zadání pozdějšího času odjezdu, než je aktuální čas. Pokud chcete zadat PROGNÓZU, zapište nejdříve pobyt.
train_confirm_filter=Potvrzení vlaků:
train_train_filter=Zobrazit vlaky:
clear=Smazat
all=všechny
confirmed=potvrzené
unconfirmed=nepotvrzené
incoming=končící
departing=výchozí
departing_and_incoming=končící + výchozí
activeonly=tranzitní
operating_notes=Další pokyny
sheduled_arrival=Plánovaný|příjezd
train_route_sheduled_arrival=Plánovaný příjezd
real_arrival=Skutečný|příjezd
train_route_real_arrival=Skutečný příjezd
train_type=Typ
train_type_full=Typ vlaku
train_type_type=Typ vlaku
train_number=Číslo vlaku
train_number_full=Číslo vlaku
from_post=Z
train_name=Název vlaku
to_post=Do
train_track=Kolej
line_number=Číslo trati
train_stop_duration=Pobyt
stop_type=Důvod|pobytu
sheduled_departure=Plánovaný|odjezd
train_route_sheduled_departure=Plánovaný odjezd
real_departure=Skutečný|odjezd
train_route_real_departure=Skutečný odjezd
star_station=Výchozí stanice
terminus_station=Cílová stanice
carrier=Dopravce
carrier_shortcut=Dopr.
train_list=Seznam vlaků
train_description=Informace o vlaku
train_route=Jízdní řád
additional_information=Dodatečné informace
from=Ze stanice
to=Do stanice
polish=Polski
english=English
timetable_type=Typ jízdního řádu
own_notes=Vlastní poznámky
individual=Individuální
yearly=Roční
is_over_gauge_cargo=Překročená ložná míra
is_dangerous_cargo=Nebezpečná zásilka
is_high_risk_cargo=Velmi nebezpečná zásilka
is_overweight_cargo=Překročená hmotnost
is_other_exceptional_cargo=Jiná mimořádnost
operating=K
canceled=N|K
timetable_head_l=L
timetable_head_peron_track=P T
train_route_confirmed=C
train_route_hour=Hodina
train_route_type=Typ
train_route_station=Stanice
train_route_train_stop_calculated_duration=Pobyt ve stanici
train_route_stop_type=Důvod pobytu
train_route_dot=*
train_route_line_number=Trať
train_route_train=Vlak:
train_route_relation=Jízda:


time_enter_button=Vložení informací
time_enter_modal_title=Reálný čas příjezdu a odjezdu
time_enter_modal_train_arrived=Příjezd vlaku:
time_enter_modal_train_departured=Čas odjezdu:
time_enter_modal_delay_collision=Srážka
time_enter_modal_delay_accident_on_crossing=Nehoda na přejezdu
time_enter_modal_delay_network_damage=Poškození trolejového vedení
time_enter_modal_delay_locomotive_defect=Poškození lokomotivy
time_enter_modal_train_add_arrival_minutes_number=Přidat k času příjezdu
time_enter_modal_train_add_arrival_minutes_text=Přidat k času příjezdu - text
time_enter_modal_train_add_departure_minutes_number=Přidat k času odjezdu
time_enter_modal_train_add_departure_minutes_text=Přidat k času odjezdu - text
time_enter_modal_minute_shortcut=min
time_enter_modal_button_train_stop=Zapsat pobyt
time_enter_modal_button_train_release_stop=Rušení zapsaného pobytu
time_enter_modal_button_save=Uložit
time_enter_modal_button_cancel=Zpět
time_enter_modal_button_rewrite_arrival_time=Zkopír. čas příjezdu
ok=OK
message=Informace
cancel=Zpět
warning=Varování
time_enter_modal_error_departure_time_lower_arrival=Čas odjezdu nesmí být dřívější než čas příjezdu.
time_enter_modal_warning_departure_time_greater_actual=Proběhl pokus o zadání pozdějšího času, než je aktuální čas. Přejete si zadat prognózu?
time_enter_modal_error_departure_time_greater_actual_prognosis=Není možné zrušit zastavení, pokud je stále zadána PROGNÓZA. Zadejte prosím čas odjezdu vlaku.
time_enter_modal_save_success=Uloženo
time_enter_modal_save_failure=Došlo k chybě
time_enter_modal_save_failure_no_permission=Čas zapsán sousedním výpravčím.


context_menu_enter_passing_through_time=Potvrzení času průjezdu
context_menu_enter_arrival_time=Potvrzení času příjezdu
context_menu_enter_departure_time=Potvrzení času odjezdu
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
time_enter_modal_save_failure_train_too_away=Vlak je příliš daleko pro potvrzení dat
time_enter_modal_save_failure_train_not_exist=Vlak ještě nevyjel nebo už dojel
connection_lost_reconnecting=Spojení se serverem bylo ztraceno. Server se pravděpodobně restartuje. Probíhá pokus o opětovné připojení.
connection_lost_disconnected=Spojení se serverem bylo ztraceno. Použijte "Další akce pro odeslání" -> "Znovu načíst jízdní řády" v levém horním rohu obrazovky.
SChinese=简体中文
TChinese=繁體中文
