

full_date=Datum anzeigen:
train_number_filter=Zugnummer:
train_confirm_filter=Bestätigungen:
train_train_filter=Züge:
clear=Löschen
all=Alle
confirmed=Bestätigt
unconfirmed=Unbestätigt
incoming=eingehend
departing=ausgehend
activeonly=fahrend
operating_notes=Betriebshinweise
sheduled_arrival=Geplante Ankunftszeit
train_route_sheduled_arrival=Geplante Ankunftszeit
real_arrival=Tatsächliche Ankunftszeit
train_route_real_arrival=Tatsächliche Ankunftszeit
train_type=Typ
train_type_full=Zugart
train_number=Zugnr.
train_number_full=Zugnummer
from_post=Von Betriebsstelle
train_name=Zugname
to_post=Nach Betriebsstelle
train_track=Gleis
line_number=Lin. Nr.
train_stop_duration=Halt
stop_type=Halttyp
train_route_sheduled_departure=Geplante Abfahrtszeit
train_route_real_departure=Tatsächliche Abfahrtszeit
real_departure=Tatsächliche Abfahrtszeit
star_station=Startbahnhof
terminus_station=Endbahnhof
carrier=Betreiber
carrier_shortcut=B
train_list=Zugliste
train_route=Zugfahrplan
additional_information=Zusätzliche Informationen
from=Von
to=Nach
polish=Polski
english=English
timetable_type=Art des Fahrplanes
own_notes=Eigene Notizen
individual=Einmalig
is_over_gauge_cargo=Überbreite
is_high_risk_cargo=Fracht mit besonders hohem Risiko
is_overweight_cargo=Fracht mit Übergewicht
is_other_exceptional_cargo=Sonstige
operating=F
canceled=F|N
timetable_head_l=L
timetable_head_peron_track=B G
train_route_confirmed=B
train_route_hour=Stunde
train_route_type=Typ
train_route_train_stop_calculated_duration=Aufenthalt
train_route_stop_type=Halttyp
train_route_dot=*
train_route_line_number=Lin. Nr.
train_route_train=Zug:
train_route_relation=Zugverbindung:
time_enter_modal_train_arrived=Ankunftszeit:
time_enter_modal_train_departured=Abfahrtszeit:
time_enter_modal_delay_collision=Kollision
time_enter_modal_delay_accident_on_crossing=Unfall auf dem Bahnübergang
time_enter_modal_delay_network_damage=Schaden an der Oberleitung
time_enter_modal_delay_locomotive_defect=Technischer Defekt am Zug
time_enter_modal_train_add_arrival_minutes_number=Zur Ankunftszeit hinzufügen
time_enter_modal_train_add_departure_minutes_number=Zur Abfahrtszeit hinzufügen
time_enter_modal_train_add_departure_minutes_text=Kontext zur Abfahrtszeit hinzufügen
time_enter_modal_minute_shortcut=min
time_enter_modal_button_train_stop=Prognose bestätigen (Zug angehalten)
time_enter_modal_button_train_release_stop=Haltestelle freigeben (Zug eingeben)
time_enter_modal_button_save=Speichern
time_enter_modal_button_cancel=Abbrechen
ok=OK
message=Nachricht
cancel=Abbrechen
warning=Warnung
time_enter_modal_error_departure_time_lower_arrival=Die Abfahrtszeit darf nicht vor der Ankunftszeit erfolgen.
time_enter_modal_error_departure_time_greater_actual=Es wurde versucht, eine Abfahrtszeit einzugeben, die nach der aktuellen Zeit liegt. Wenn Sie eine PROGNOSE eingeben wollen, geben Sie zuerst ein HALT ein.
time_enter_modal_error_departure_time_greater_actual_prognosis=Es ist nicht möglich, einen Halt während der Eingabe der Prognose zu löschen. Bitte geben Sie die Abfahrtszeit des Zuges ein.
time_enter_modal_save_success=Erfolgreich gespeichert
time_enter_modal_save_failure=Ein Fehler ist aufgetreten
time_enter_modal_save_failure_no_permission=Die tatsächliche Zeit, die vom Fahrdienstleiter an der nächsten Station genehmigt wurde.


context_menu_enter_passing_through_time=Durchfahrtszeit bestätigen
context_menu_enter_arrival_time=Ankunftszeit bestätigen
context_menu_enter_departure_time=Abfahrtszeit bestätigen
English=Englisch
Polish=Polnisch
Italian=Italiano
Russian=Russisch
Hungarian=Magyar
French=Français
time_enter_modal_warning_departure_time_greater_actual=Es wurde versucht, eine Uhrzeit einzugeben, die nach der aktuellen Uhrzeit liegt. Möchten Sie eine Prognose eingeben?
# Description
post=Posten:
departing_and_incoming=ein- und ausgehend
train_type_type=Zuggattung
German=Deutsch
Spanish=Spanisch
Czech=Čeština
sheduled_departure=Geplante Abfahrtszeit
train_description=Zugdetails
yearly=Jährlich
is_dangerous_cargo=Gefahrgut
train_route_station=Haltestelle


time_enter_button=Zeit manuell bearbeiten
time_enter_modal_title=Ankunfts- und Abfahrtszeit bearbeiten
time_enter_modal_train_add_arrival_minutes_text=Kontext zur Ankunftszeit hinzufügen
time_enter_modal_button_rewrite_arrival_time=Ankunftszeit kopieren
time_enter_modal_error_arrival_time_greater_actual=Es wurde versucht, eine spätere Ankunftszeit als die derzeitige anzugeben.
time_enter_modal_save_failure_train_too_away=Der Zug ist zu weit entfernt, um die Daten zu bestätigen
time_enter_modal_save_failure_train_not_exist=Der Zug ist noch nicht gestartet oder bereits fertig gefahren
connection_lost_reconnecting=Die Verbindung zum Fahrplanserver ist unterbrochen. Wahrscheinlich wird der Server gerade neu gestartet. Versuchen Sie, die Verbindung wieder herzustellen.
connection_lost_disconnected=Verbindung zum Fahrplan-Server verloren. Verwende "Fahrdienstleiteraktionen" -> "EDR neu laden" in der linken oberen Ecke des GUI.
SChinese=简体中文
TChinese=繁體中文
