# Description
post=Post:
full_date=Full date:
train_number_filter=Train number:
train_confirm_filter=Confirmation:
train_train_filter=Trains:
clear=Clear
all=all
confirmed=confirmed
unconfirmed=unconfirmed
incoming=terminating
departing=starting
departing_and_incoming=terminating + starting
activeonly=running
operating_notes=Operating notes
sheduled_arrival=Scheduled|arrival
train_route_sheduled_arrival=Sched. arrival
real_arrival=Real|arrival
train_route_real_arrival=Real arrival
train_type=Type
train_type_full=Train type
train_type_type=Train type
train_number=Train no
train_number_full=Train number
from_post=From post
train_name=Train name
to_post=To post
train_track=Track
line_number=Line no.
train_stop_duration=Layover
stop_type=Stop type
sheduled_departure=Scheduled|departure
train_route_sheduled_departure=Shed. departure
real_departure=Real|departure
train_route_real_departure=Real departure
star_station=Start station
terminus_station=Terminus station
carrier=Carrier
carrier_shortcut=C
train_list=Train list
train_description=Train description
train_route=Train route
additional_information=Additional information
from=From
to=To
polish=Polski
english=English
timetable_type=Timetable type
own_notes=Own notes
individual=Individual
yearly=Yearly
is_over_gauge_cargo=Over gauge
is_dangerous_cargo=Dangerous cargo
is_high_risk_cargo=High risk cargo
is_overweight_cargo=Overweight cargo
is_other_exceptional_cargo=Other exceptional
operating=K
canceled=N|K
timetable_head_l=L
timetable_head_peron_track=P T
train_route_confirmed=C
train_route_hour=Hour
train_route_type=Type
train_route_station=Station
train_route_train_stop_calculated_duration=Layover
train_route_stop_type=Stop type
train_route_dot=*
train_route_line_number=Line no
train_route_train=Train:
train_route_relation=Relation:


time_enter_button=Time enter
time_enter_modal_title=Real train arrival and departure time
time_enter_modal_train_arrived=Train arrived:
time_enter_modal_train_departured=Train departure:
time_enter_modal_delay_collision=Collision
time_enter_modal_delay_accident_on_crossing=Accident on the crossing
time_enter_modal_delay_network_damage=Catenary damage
time_enter_modal_delay_locomotive_defect=Locomotive defect
time_enter_modal_train_add_arrival_minutes_number=Add to arrival time
time_enter_modal_train_add_arrival_minutes_text=Add to arrival time - text
time_enter_modal_train_add_departure_minutes_number=Add to departure time
time_enter_modal_train_add_departure_minutes_text=Add to departure time - text
time_enter_modal_minute_shortcut=min
time_enter_modal_button_train_stop=Enter stop (train STOP)
time_enter_modal_button_train_release_stop=Release stop (train STOP)
time_enter_modal_button_save=Save
time_enter_modal_button_cancel=Cancel
time_enter_modal_button_rewrite_arrival_time=Copy arrival time
ok=OK
message=Message
cancel=Cancel
warning=Warning
time_enter_modal_error_departure_time_lower_arrival=The departure time must not be earlier than the arrival time.
time_enter_modal_error_arrival_time_greater_actual=There has been an attempt to give an arrival time later than the current one.
time_enter_modal_error_departure_time_greater_actual=An attempt was made to enter a departure time later than the current time. If you want to enter a PROGNOSIS, enter a STOP first.
time_enter_modal_warning_departure_time_greater_actual=There has been an attempt to enter a time later than the current time. Do you wish to enter a prognosis?
time_enter_modal_error_departure_time_greater_actual_prognosis=It is not possible to cancel a stop while PROGNOSIS is still entered. Please set the train departure time.
time_enter_modal_save_success=Saved
time_enter_modal_save_failure=An error has occurred
time_enter_modal_save_failure_no_permission=Time actually approved by the dispatcher at the next station.


context_menu_enter_passing_through_time=Confirm crossing time
context_menu_enter_arrival_time=Confirm arrival time
context_menu_enter_departure_time=Confirm departure time
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
time_enter_modal_save_failure_train_too_away=The train is too far away to confirm data
time_enter_modal_save_failure_train_not_exist=The train has not yet started or has already finished running
connection_lost_reconnecting=Connection lost to timetable server. The server is probably being restarted. Trying to reconnect.
connection_lost_disconnected=Connection lost to timetable server. Use "Additional outpost actions" -> "Reload Timetable" in top left GUI corner.
SChinese=简体中文
TChinese=繁體中文
