

time_enter_modal_delay_network_damage=Daños en catenarias
time_enter_modal_train_add_arrival_minutes_number=Añadir al tiempo de llegada


context_menu_enter_passing_through_time=Confirmar hora de paso
context_menu_enter_departure_time=Confirmar hora de salida
# Description
post=Puesto:
full_date=Fecha completa:
train_number_filter=Num. tren:
train_confirm_filter=Confirmación:
train_train_filter=Trenes:
clear=Borrar
confirmed=Confirmados
unconfirmed=No confirmados
incoming=Finalizando
departing_and_incoming=Terminando + iniciando
activeonly=Circulando
operating_notes=Notas de servicio
sheduled_arrival=Horario|llegada
train_route_sheduled_arrival=Hora llegada
real_arrival=Real|llegada
train_type=Tipo
train_type_full=Tipo tren
train_type_type=Tipo tren
train_number=No. tren
train_number_full=Número tren
from_post=Desde estación
train_name=Nombre tren
to_post=Hacia estación
train_track=Vía
line_number=No. línea
train_stop_duration=Parada
stop_type=Tipo parada
train_route_sheduled_departure=Horario salida
real_departure=Real|salida
train_route_real_departure=Real salida
star_station=Estación inicio
terminus_station=Estación final
carrier=Operador
carrier_shortcut=C
train_list=Lista de trenes
train_route=Ruta del tren
from=Desde
to=Hacia
polish=Polski
english=English
own_notes=Notas propias
individual=Individual
is_over_gauge_cargo=Exceso de gálibo
is_high_risk_cargo=Carga alto riesgo
operating=K
canceled=N|K
timetable_head_l=L
train_route_confirmed=C
train_route_hour=Hora
train_route_type=Tipo
train_route_train_stop_calculated_duration=Parada
train_route_stop_type=Tipo parada
train_route_dot=*
train_route_line_number=No. línea
train_route_train=Tren:
train_route_relation=Relación:


time_enter_button=Entrada manual
time_enter_modal_title=Hora real de llegada y salida del tren
time_enter_modal_train_arrived=Tren llegó:
time_enter_modal_train_departured=Tren salió:
time_enter_modal_delay_collision=Colisión
time_enter_modal_delay_accident_on_crossing=Accidente en paso a nivel
time_enter_modal_delay_locomotive_defect=Locomotora averiada
time_enter_modal_train_add_arrival_minutes_text=Añadir a hora de llegada - texto
time_enter_modal_train_add_departure_minutes_text=Agregar a la hora de salida - texto
time_enter_modal_button_train_release_stop=Liberar parada (PARADA tren)
ok=Aceptar
message=Mensaje
cancel=Cancelar
warning=Alerta
time_enter_modal_error_arrival_time_greater_actual=Se ha intentado dar una hora de llegada posterior a la actual.
time_enter_modal_warning_departure_time_greater_actual=Se ha intentado introducir una hora posterior a la actual. ¿Deseas introducir un pronóstico?
time_enter_modal_error_departure_time_greater_actual_prognosis=No es posible cancelar una parada mientras se sigue introduciendo PROGNÓSTICO. Por favor, ajusta la hora de salida del tren.
time_enter_modal_save_success=Guardado
time_enter_modal_save_failure=Se ha producido un error
time_enter_modal_save_failure_no_permission=Tiempo actualmente aprobado por el controlador en la siguiente estación.
context_menu_enter_arrival_time=Confirmar hora de llegada
English=English
Polish=Polaco
German=Deutsch
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
Italian=Italiano
time_enter_modal_train_add_departure_minutes_number=Añadir a hora de salida
time_enter_modal_minute_shortcut=min
all=Todos
time_enter_modal_button_train_stop=Introducir parada (PARADA tren)
departing=Iniciando
time_enter_modal_button_save=Guardar
train_route_real_arrival=Real llegada
time_enter_modal_button_cancel=Cancelar
sheduled_departure=Horario|salida
time_enter_modal_button_rewrite_arrival_time=Copiar hora llegada
train_description=Descripción del tren
additional_information=Información adicional
timetable_type=Tipo de horario
yearly=Anual
is_dangerous_cargo=Carga peligrosa
is_overweight_cargo=Carga muy pesada
is_other_exceptional_cargo=Otros especiales
time_enter_modal_error_departure_time_lower_arrival=La hora de salida no debe ser anterior a la de llegada.
timetable_head_peron_track=P T
train_route_station=Estación
time_enter_modal_error_departure_time_greater_actual=Se ha intentado introducir una hora de salida posterior a la hora actual. Si deseas introducir un PRONÓSTICO, introduzca primero una PARADA.
time_enter_modal_save_failure_train_too_away=El tren está demasiado lejos para confirmar los información
time_enter_modal_save_failure_train_not_exist=El tren aún no ha arrancado o ya ha terminado de circular
connection_lost_reconnecting=Se ha perdido la conexión con el servidor de horarios. Probablemente se está reiniciando el servidor. Intentando reconectar.
connection_lost_disconnected=Se ha perdido la conexión con el servidor de horarios. Utiliza "Acciones adicionales del puesto avanzado" -> "Recargar horario" en la esquina superior izquierda de la Interfaz.
SChinese=简体中文
TChinese=繁體中文
