

additional_information=Information complémentaire
polish=Polski
english=English
own_notes=Commentaires personnels
yearly=Annuel
is_over_gauge_cargo=Hors gabarit
is_overweight_cargo=Marchandises lourdes
is_other_exceptional_cargo=Autres exceptionnels
canceled=N|K
train_route_stop_type=Type d'arrêt
time_enter_modal_delay_locomotive_defect=Panne engin moteur
time_enter_modal_train_add_arrival_minutes_number=Ajouter à l'heure d'arrivée
time_enter_modal_train_add_arrival_minutes_text=Ajouter à l'heure d'arrivée - texte
time_enter_modal_train_add_departure_minutes_number=Ajouter à l'heure de départ
time_enter_modal_train_add_departure_minutes_text=Ajouter à l'heure de départ - text
time_enter_modal_button_rewrite_arrival_time=Copier l'heure d'arrivée
sheduled_departure=Départ|prévu
train_train_filter=Trains :
all=tout
incoming=arrivées
sheduled_arrival=Arrivée|prévue
real_arrival=Arrivée|réelle
activeonly=en circulation
operating_notes=Consignes d’exploitation
train_route_sheduled_arrival=Arrivée prévue
train_type=Type
train_type_full=Type de train
train_type_type=Type de train
train_number_full=Numéro de train
line_number=Ligne n°
real_departure=Départ|réel
carrier=Compagnie
train_list=Liste des trains
train_route=Sillon
from=De
to=A
timetable_type=Type d'horaire
individual=Individuel
is_dangerous_cargo=Matières dangereuses
is_high_risk_cargo=Marchandises à haut-risque
operating=K
timetable_head_l=L
timetable_head_peron_track=Q V
train_route_confirmed=C
train_route_hour=Heure
train_route_type=Type
train_route_station=Gare
train_route_train_stop_calculated_duration=Arrêt
train_route_dot=*
train_route_line_number=Ligne n°
train_route_train=Train :


time_enter_button=Saisie de l'heure
time_enter_modal_title=Arrivée réelle du train et heure de départ
time_enter_modal_delay_collision=Collision
time_enter_modal_delay_accident_on_crossing=Accident à un passage à niveau
time_enter_modal_delay_network_damage=Incident caténaire
time_enter_modal_train_arrived=Train arrivé :
time_enter_modal_train_departured=Train parti :
time_enter_modal_minute_shortcut=min
time_enter_modal_button_train_stop=Créer un sillon (train STOP)
time_enter_modal_button_train_release_stop=Libérer le sillon (train STOP)
ok=OK
message=Message
cancel=Annuler
warning=Attention
time_enter_modal_button_cancel=Annuler
time_enter_modal_error_arrival_time_greater_actual=Il y a eu une tentative de donner une heure d'arrivée plus tardive que l'heure actuelle.


context_menu_enter_passing_through_time=Confirmer l'heure de passage
context_menu_enter_arrival_time=Confirmer l'heure d'arrivée
context_menu_enter_departure_time=Confirmer l'heure de départ
English=English
time_enter_modal_error_departure_time_lower_arrival=L'heure de départ ne peut pas être aussi proche de l'heure d'arrivée.
time_enter_modal_save_failure_no_permission=Horaire approuvé par l'aiguilleur de la prochaine gare.
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
departing_and_incoming=Arrivées + départs
time_enter_modal_error_departure_time_greater_actual=Une tentative a été faite pour entrer une heure de départ postérieure à l'heure actuelle. Si vous voulez saisir un PRONOSTIC, saisissez d'abord un STOP.
time_enter_modal_button_save=Sauvegarder
time_enter_modal_warning_departure_time_greater_actual=Il y a eu une tentative d'entrer une heure postérieure à l'heure actuelle. Souhaitez-vous saisir un pronostic ?
full_date=Date complète :
train_route_real_arrival=Arrivée réelle
train_number=Train n°
from_post=Provenance
train_name=Nom du train
train_number_filter=Numéro de train :
to_post=Destination
train_track=Voie
train_stop_duration=Arrêt
stop_type=Type d'arrêt
# Description
post=Poste :
train_confirm_filter=Confirmation :
clear=Effacer
train_route_sheduled_departure=Départ prévu
confirmed=confirmé
train_route_real_departure=Départ réel
star_station=Gare origine
time_enter_modal_error_departure_time_greater_actual_prognosis=Il n'est pas possible d'annuler un arrêt alors que le PROGNOSTIC est encore saisi. Veuillez définir l'heure de départ du train.
unconfirmed=non-confirmé
terminus_station=Gare terminus
time_enter_modal_save_success=Sauvegardé
departing=départs
carrier_shortcut=C
time_enter_modal_save_failure=Une erreur est survenue
train_description=Description du train
train_route_relation=Relation :
time_enter_modal_save_failure_train_too_away=Le train est trop éloigné pour confirmer les données
time_enter_modal_save_failure_train_not_exist=Le train ne circule pas encore ou il est déjà arrivé à destination
connection_lost_reconnecting=Perte de connexion au serveur d'horaires. Le serveur est probablement en train de redémarrer. Tentative de reconnexion en cours.
connection_lost_disconnected=Perte de connexion au serveur d'horaires. Utilisez l'option "Actions supplémentaires du poste" -> "Recharger l'horaire" dans le coin supérieur gauche de l'interface graphique.
SChinese=简体中文
TChinese=繁體中文
