

train_route_sheduled_arrival=Menetrend szerinti érkezés
real_arrival=Valós érkezés
train_route_real_arrival=Valós érkezés
all=Összes
clear=Törlés
departing=Indul
departing_and_incoming=Érkezik+Indul
activeonly=Áthalad
operating_notes=Üzemnapló
incoming=Érkezik
train_type=Típus
train_type_full=Vonatnem
train_type_type=Vonat típusa
train_number=Vonatszám
train_number_full=Vonatszám
sheduled_arrival=Menetrend szerinti érkezés
english=English
polish=Polski
French=Français
Italian=Italiano
English=Angol
Polish=Lengyel
German=Deutsch
Russian=Русский
Spanish=Spanyol
Czech=Čeština
ok=Ok
message=Üzenet
cancel=Visszavonás
warning=Figyelmeztetés
Hungarian=Magyar
# Description
post=Hozzászólás:
full_date=Teljes dátum:
train_number_filter=Vonat száma:
train_confirm_filter=Jóváhagyás:
train_train_filter=Vonatok:
confirmed=megerősít
unconfirmed=Nem megerősített
train_stop_duration=Átszállás
from_post=A posztról
train_name=Vonat neve
to_post=Postázás
train_track=Vágány
line_number=Vonalszám.
sheduled_departure=Menetrend szerinti indulás
train_route_sheduled_departure=Tervezett indulás
stop_type=Megálló típusa
real_departure=Valódi|indulás
train_route_real_departure=Tényleges indulás
star_station=Indító állomás
terminus_station=Végső állomás
carrier=Karrier
train_list=Vonatok listája
train_description=A vonat leírása
train_route=Menetrend
additional_information=További információ
from=Az állomásról
to=Az állomásra
timetable_type=Ütemezés típusa
carrier_shortcut=Közlekedés
own_notes=Saját jegyzetek
individual=Egyedi
yearly=Évi
is_over_gauge_cargo=Túlméretes tehervonat
is_dangerous_cargo=Veszélyes tehervonat
is_high_risk_cargo=Magas kockázatú rakomány
is_overweight_cargo=Túlsúlyos rakomány
is_other_exceptional_cargo=Egyéb kivételes
operating=K
canceled=N|K
train_route_type=Típus
timetable_head_l=L
timetable_head_peron_track=P T
train_route_confirmed=C
train_route_hour=Óra
train_route_station=Állomás
train_route_stop_type=Stop típus
train_route_dot=.
train_route_line_number=Vonalszám
train_route_train=Vonat:
train_route_relation=Kapcsolat:


time_enter_button=Idő belépés
time_enter_modal_title=Valós érkezési és indulási idő
time_enter_modal_train_arrived=Megérkezett a vonat:
time_enter_modal_train_departured=Elindult a vonat:
time_enter_modal_delay_collision=Ütközés
time_enter_modal_delay_network_damage=A felsővezeték károsodása
time_enter_modal_delay_locomotive_defect=Mozdony hiba
time_enter_modal_train_add_arrival_minutes_number=Hozzáadás az érkezési időhöz
time_enter_modal_train_add_arrival_minutes_text=Hozzáadás az érkezési időhöz - szöveg
time_enter_modal_train_add_departure_minutes_number=Hozzáadás az indulási időhöz
time_enter_modal_button_save=Mentés
time_enter_modal_button_cancel=Vissza
time_enter_modal_button_rewrite_arrival_time=Érkezési idő másolása
time_enter_modal_error_departure_time_lower_arrival=Az indulási idő nem lehet korábbi, mint az érkezési idő.
time_enter_modal_error_arrival_time_greater_actual=A jelenleginél későbbi érkezési időt próbáltál megadni.
time_enter_modal_error_departure_time_greater_actual=Kísérlet történt a jelenleginél későbbi indulási időpont megadására. Ha PROGNÓZIS-t szeretnél megadni, először írjd be a STOP-ot.
time_enter_modal_warning_departure_time_greater_actual=Kísérlet történt a jelenleginél későbbi időpont megadására. Szeretnél előrejelzést adni?
time_enter_modal_error_departure_time_greater_actual_prognosis=A megállást nem lehet törölni, amíg a PROGNÓZIS még be van írva. Kérlek, állítsd be a vonat indulási idejét.
time_enter_modal_save_success=Elmentve
time_enter_modal_save_failure=Hiba történt
time_enter_modal_save_failure_no_permission=A következő állomáson a diszpécser által ténylegesen jóváhagyott idő.


context_menu_enter_passing_through_time=Erősítsd meg az indulási/átkelési időt
context_menu_enter_arrival_time=Erősítsd meg érkezési időt
context_menu_enter_departure_time=Erősítsd meg az indulási időt
time_enter_modal_train_add_departure_minutes_text=Hozzáadás az indulási időhöz - szöveg
time_enter_modal_minute_shortcut=Perc
time_enter_modal_button_train_stop=Írd be a megállót (vonat STOP)
time_enter_modal_button_train_release_stop=Megálló feloldása (vonat STOP)
time_enter_modal_save_failure_train_too_away=A vonat túl messze van az információ megerősítéséhez
time_enter_modal_save_failure_train_not_exist=A vonat még nem indult, vagy már megérkezett
train_route_train_stop_calculated_duration=Állj meg
time_enter_modal_delay_accident_on_crossing=Baleset egy vasúti átjárónál
connection_lost_reconnecting=Megszakadt a kapcsolat a menetrendi szerverrel. A szerver valószínűleg újraindul. Újra csatlakozni próbálj.
connection_lost_disconnected=Megszakadt a kapcsolat a menetrendi szerverrel. Használja a "További előőrs-műveletek" -> "Időtár újratöltése" lehetőséget a grafikus felhasználói felület bal felső sarkában.
SChinese=简体中文
TChinese=繁體中文
