full_date=Data completa:
train_number_filter=Treno numero:
is_dangerous_cargo=Merci pericolose
is_overweight_cargo=Merci pesanti
train_route_confirmed=C
train_route_hour=Ora
train_confirm_filter=Conferma:
train_train_filter=Treni:
clear=Libero
confirmed=Confermato
unconfirmed=Non confermato
departing=Partenza
incoming=Terminazione
activeonly=in corsa
operating_notes=Note operative
sheduled_arrival=Arrivo|programmato
real_arrival=Arrivo effettivo
train_route_real_arrival=Arrivo effettivo
train_type=Tipo
train_type_full=Tipo di treno
train_type_type=Tipo di treno
train_number=Treno n
train_number_full=Treno numero
line_number=Linea n.
train_stop_duration=Fermata
stop_type=Tipo di fermata
real_departure=Partenza effettiva
train_route_real_departure=Partenza effettiva
star_station=Stazione di origine
terminus_station=Stazione di destinazione
carrier_shortcut=IF
train_route=Percorso del treno
from=Da
to=A
polish=Polski
timetable_type=Tipo di orario
own_notes=Note proprie
is_over_gauge_cargo=Treno merci sovradimensionato
is_high_risk_cargo=Merci ad alto rischio
is_other_exceptional_cargo=Altro eccezionale
operating=K
canceled=N|K
timetable_head_l=L
timetable_head_peron_track=P T
train_route_type=Tipo
train_route_station=Stazione
train_route_stop_type=Tipo di fermata
train_route_line_number=Linea n
train_route_train=Treno:
train_route_relation=Tratta:
time_enter_modal_title=Arrivo effettivo del treno e orario di partenza
time_enter_modal_train_departured=Partenza del treno:
time_enter_modal_delay_network_damage=Danni alla catenaria
time_enter_modal_train_add_arrival_minutes_number=Aggiungere all'orario di arrivo
time_enter_modal_train_add_departure_minutes_number=Aggiungere all'orario di partenza
time_enter_modal_minute_shortcut=min
train_route_train_stop_calculated_duration=Fermata
time_enter_modal_button_save=Salva
time_enter_modal_button_cancel=Annulla
time_enter_modal_button_rewrite_arrival_time=Copia orario di arrivo
ok=OK
message=Messaggio
cancel=Annulla
warning=Attenzione
time_enter_modal_error_arrival_time_greater_actual=Si è cercato di indicare un orario di arrivo successivo a quello attuale.
time_enter_modal_warning_departure_time_greater_actual=Si è tentato di inserire un orario successivo a quello attuale. Si desidera inserire una previsione?
time_enter_modal_save_failure_no_permission=Orario approvato dal regolatore di circolazione della stazione successiva.


context_menu_enter_passing_through_time=Conferma orario di transito
context_menu_enter_arrival_time=Conferma orario di arrivo
context_menu_enter_departure_time=Conferma orario di partenza
time_enter_modal_save_success=Salvato
time_enter_modal_save_failure=Si è verificato un errore
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
train_route_dot=*


time_enter_button=Inserimento orario
time_enter_modal_train_arrived=Arrivo del treno:
all=Tutti
time_enter_modal_delay_collision=Collisione
departing_and_incoming=Terminazione + partenza
train_route_sheduled_arrival=Arrivo programmato
from_post=Provenienza
train_name=Categoria treno
time_enter_modal_delay_accident_on_crossing=Incidente al passaggio a livello
time_enter_modal_button_train_release_stop=Annullamento della fermata (treno STOP)
to_post=Destinazione
time_enter_modal_delay_locomotive_defect=Guasto alla locomotiva
time_enter_modal_error_departure_time_lower_arrival=L'orario di partenza non deve essere in anticipo rispetto all'orario di arrivo.
train_track=Binario
time_enter_modal_train_add_arrival_minutes_text=Aggiungere all'orario di arrivo - testo
sheduled_departure=Partenza programmata
train_route_sheduled_departure=Partenza programmata
carrier=Impresa ferroviaria
train_list=Elenco dei treni
train_description=Descrizione del treno
additional_information=Ulteriori informazioni
time_enter_modal_train_add_departure_minutes_text=Aggiungere all'orario di partenza - testo
time_enter_modal_error_departure_time_greater_actual_prognosis=Non è possibile annullare una fermata mentre è ancora in corso l'inserimento del PRONOSTICO. Impostare l'orario di partenza del treno.
english=English
time_enter_modal_error_departure_time_greater_actual=Si è tentato di inserire un orario di partenza successivo a quello attuale. Se si desidera inserire un PRONOSTICO, inserire prima uno STOP.
individual=Individuale
time_enter_modal_button_train_stop=Inserire la fermata (treno STOP)
# Description
post=Stazione:
yearly=Annuale
time_enter_modal_save_failure_train_not_exist=Il treno non è ancora partito o ha già terminato la sua corsa
time_enter_modal_save_failure_train_too_away=Il treno è troppo lontano per poter confermare i dati
connection_lost_reconnecting=La connessione al server degli orari è stata interrotta. Probabilmente il server è in fase di riavvio. Tentativo di riconnessione.
connection_lost_disconnected=Connessione persa al server degli orari. Selezionare "Azioni aggiuntive" -> "Aggiorna orario" in alto a sinistra.
SChinese=简体中文
TChinese=繁體中文
