

French=Français
all=wszystkie
confirmed=potwierdzone
unconfirmed=niepotwierdzone
incoming=kończące
departing=uruchamiane
departing_and_incoming=uruch. + koń.
activeonly=kursujące
operating_notes=Uwagi eksploatacyjne
sheduled_arrival=Przyjazd plan.
train_route_sheduled_arrival=Przyjazd pl.
real_arrival=Przyjazd rzecz.
train_route_real_arrival=Przyjazd rz.
train_type=Rodz.
train_type_full=Rodzaj pociągu
train_type_type=Typ pociągu
train_number=Nr poc
train_number_full=Numer pociągu
from_post=Z kierunku post.
to_post=W kierunku post.
train_track=Tor
line_number=Nr L.
train_stop_duration=Postój
stop_type=Typ p.
sheduled_departure=Odjazd plan.
train_route_sheduled_departure=Odjazd pl.
real_departure=Odjazd rzecz.
train_route_real_departure=Odjazd rz.
star_station=Stacja początkowa
terminus_station=Stacja końcowa
carrier=Przewoźnik
train_list=Wykaz pociągów
train_description=Opis pociągu
train_route=Trasa pociągu
additional_information=Dodatkowe informacje
from=Z
to=Do
polish=Polski
english=English
timetable_type=Rodzaj rozkładu jazdy
own_notes=Uwagi własne
individual=Indywidualny
yearly=Roczny
is_over_gauge_cargo=Przekroczona skrajna
is_dangerous_cargo=Towar niebezpieczny
is_high_risk_cargo=Towar wysokiego ryzyka
is_overweight_cargo=Przekroczony nacisk
is_other_exceptional_cargo=Inne nadzwyczajne
operating=K
canceled=N|K
timetable_head_l=L
timetable_head_peron_track=P T
train_route_confirmed=Z
train_route_hour=Godz.
train_route_type=Rodzaj
train_route_station=Stacja
train_route_train_stop_calculated_duration=P. obl.
train_route_stop_type=Typ postoju
train_route_dot=*
train_route_line_number=Nr linii
train_route_train=Pociąg:
train_route_relation=Relacja:


time_enter_button=Wprowadzanie godzin
time_enter_modal_title=Rzeczywisty czas przyjazdu i odjazdu pociągu
time_enter_modal_train_arrived=Pociąg przyjechał:
time_enter_modal_train_departured=Pociąg odjechał:
time_enter_modal_delay_collision=Potrącenie
ok=OK
message=Komunikat
cancel=Anuluj
warning=Ostrzeżenie
time_enter_modal_error_departure_time_lower_arrival=Godzina odjazdu nie może być wcześniejsza niż godzina przyjazdu.
time_enter_modal_error_arrival_time_greater_actual=Nastąpiła próba podania godziny przyjazdu późniejszej niż obecna.
time_enter_modal_error_departure_time_greater_actual=Nastąpiła próba podania godziny odjazdu późniejszej niż obecna. Jeżeli chcesz wprowadzić PROGNOZĘ - najpierw wprowadź POSTÓJ.
time_enter_modal_warning_departure_time_greater_actual=Nastąpiła próba wprowadzenia godziny późniejszej niż obecna. Czy chcesz wprowadzić prognozę?
time_enter_modal_error_departure_time_greater_actual_prognosis=Nie można odwołać postoju gdy nadal wprowadzona jest PROGNOZA. Proszę ustawić czas odjazdu pociągu.
time_enter_modal_save_success=Zapisano
time_enter_modal_save_failure=Wystąpił błąd
time_enter_modal_save_failure_no_permission=Godzina aktualnie zatwierdzona przez dyżurnego na następnej stacji.


context_menu_enter_passing_through_time=Zatwierdź godzinę przejazdu
context_menu_enter_arrival_time=Zatwierdź godzinę przyjazdu
context_menu_enter_departure_time=Zatwierdź godzinę odjazdu
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
# Description
post=Posterunek:
full_date=Pełna data:
train_number_filter=Nr pociągu:
train_confirm_filter=Potwierdzenie:
train_train_filter=Pociągi:
clear=Wyczyść
train_name=Nazwa pociągu
carrier_shortcut=P
time_enter_modal_delay_accident_on_crossing=Wypadek na przejeździe
time_enter_modal_delay_network_damage=Uszkodzenie sieci
time_enter_modal_delay_locomotive_defect=Defekt lokomotywy
time_enter_modal_train_add_arrival_minutes_number=Dodaj do czasu przyjazdu
time_enter_modal_train_add_arrival_minutes_text=Dodaj do czasu przyjazdu - teksty
time_enter_modal_train_add_departure_minutes_number=Dodaj do czasu odjazdu
time_enter_modal_train_add_departure_minutes_text=Dodaj do czasu odjazdu - teksty
time_enter_modal_minute_shortcut=min.
time_enter_modal_button_train_stop=Wprowadź postój (pociąg STÓJ)
time_enter_modal_button_train_release_stop=Odwołaj postój (pociąg STÓJ)
time_enter_modal_button_save=Zapisz
time_enter_modal_button_cancel=Anuluj
time_enter_modal_button_rewrite_arrival_time=Przepisz czas przyjazdu
time_enter_modal_save_failure_train_too_away=Pociąg jest zbyt daleko, aby zatwierdzić dane
time_enter_modal_save_failure_train_not_exist=Pociąg jeszcze nie rozpoczął biegu lub już go zakończył
connection_lost_reconnecting=Połączenie z serwerem rozkładu jazdy zostało utracone. Serwer prawdopodobnie jest uruchamiany ponownie. Próba ponownego połączenia.
connection_lost_disconnected=Połączenie z serwerem rozkładu jazdy zostało utracone. Użyj "Dodatkowe akcje posterunku" -> "Przeładuj rozkład jazdy" w lewym górnym rogu ekranu.
SChinese=简体中文
TChinese=繁體中文
