

# Description
post=Пост:
full_date=Полная дата:
unconfirmed=неподтвержденный
operating_notes=Примечания
train_name=Название поезда
to_post=Следующий пост
sheduled_departure=График|отправление
train_route_sheduled_departure=Запланированное отправление
train_route_real_departure=Реальное отправление
is_high_risk_cargo=Груз высокого риска
is_other_exceptional_cargo=Другие исключительные
timetable_head_l=L
train_route_confirmed=C
train_route_station=Станция
train_route_train_stop_calculated_duration=Остановка
train_route_stop_type=Тип стоянки
train_route_dot=*
train_route_line_number=Линия №
train_route_relation=Маршрут:


time_enter_button=Время ввода
time_enter_modal_title=Реальное время прибытия и отправления поезда
time_enter_modal_train_arrived=Поезд прибыл:
time_enter_modal_train_departured=Поезд отправился:
time_enter_modal_delay_accident_on_crossing=Несчастный случай на переезде
time_enter_modal_delay_network_damage=Повреждение контактной сети
time_enter_modal_delay_locomotive_defect=Поломка локомотива
time_enter_modal_train_add_arrival_minutes_text=Добавить к времени прибытия - текст
time_enter_modal_button_train_release_stop=Отмена остановки (остановка поезда)
warning=Предупреждение
time_enter_modal_error_departure_time_lower_arrival=Время отправления не должно быть раньше времени прибытия.
time_enter_modal_error_arrival_time_greater_actual=Была предпринята попытка указать время прибытия позже текущего.
time_enter_modal_error_departure_time_greater_actual=Была предпринята попытка ввести время отправления позже текущего. Если вы хотите ввести ПРОГНОЗ, сначала введите ОСТАНОВКУ.
train_number_filter=Номер поезда:
train_confirm_filter=Подтверждение:
train_train_filter=Поезда:
clear=Очистить
all=все
confirmed=подтвержденный
incoming=окончание
departing=начало
departing_and_incoming=окончание + начало
activeonly=курсирующие
sheduled_arrival=График прибытие
train_route_sheduled_arrival=Маршрут поезда по расписанию
real_arrival=Реальное прибытие
train_route_real_arrival=Реальное прибытие
train_type=Тип
train_type_full=Тип поезда
train_type_type=Тип поезда
train_number_full=Номер поезда
from_post=Предыдущий пост
time_enter_modal_error_departure_time_greater_actual_prognosis=Невозможно отменить остановку, пока прогноз все еще введен. Пожалуйста, установите время отправления поезда.
train_number=Поезд №
train_track=Путь
train_stop_duration=Стоянка
stop_type=Тип стоянки
real_departure=Реальное|отправление
star_station=Начальная станция
terminus_station=Конечная станция
carrier=Перевозчик
carrier_shortcut=П
train_list=Список поездов
train_description=Описание поезда
train_route=Маршрут поезда
additional_information=Дополнительная информация
from=Из
to=в
polish=Polski
english=English
timetable_type=Тип расписания
time_enter_modal_save_failure_no_permission=Время, фактически утвержденное диспетчером на следующей станции.
line_number=Линия №
own_notes=Собственные заметки
individual=Индивидуальный
yearly=Годовой
is_over_gauge_cargo=Вне шаблона
is_dangerous_cargo=Опасный груз
is_overweight_cargo=Груз с избыточным весом
operating=К
canceled=N|K
timetable_head_peron_track=P T
train_route_hour=Время
train_route_type=Тип
train_route_train=Поезд:
time_enter_modal_delay_collision=Столкновение
time_enter_modal_train_add_arrival_minutes_number=Добавить ко времени прибытия
time_enter_modal_train_add_departure_minutes_number=Добавить ко времени отправления
time_enter_modal_train_add_departure_minutes_text=Добавить ко времени отправления - текст
time_enter_modal_minute_shortcut=мин
time_enter_modal_button_train_stop=Ввести остановку (остановка поезда)
time_enter_modal_button_save=Сохранить
time_enter_modal_button_cancel=Отменить
time_enter_modal_button_rewrite_arrival_time=Скопировать время прибытия
ok=ОК
message=Сообщение
cancel=Отменить
time_enter_modal_warning_departure_time_greater_actual=Была предпринята попытка ввести время позже текущего. Вы хотите ввести прогноз?
time_enter_modal_save_success=Сохранено
time_enter_modal_save_failure=Произошла ошибка


context_menu_enter_passing_through_time=Подтвердить время проследования
context_menu_enter_arrival_time=Подтвердить время прибытия
context_menu_enter_departure_time=Подтвердить время отправления
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
Czech=Čeština
French=Français
time_enter_modal_save_failure_train_too_away=Поезд находится слишком далеко, чтобы подтвердить данные
time_enter_modal_save_failure_train_not_exist=Поезд еще не отправился или уже закончил движение
connection_lost_reconnecting=Потеряно соединение с сервером расписания. Вероятно, сервер перезапускается. Пытаемся восстановить соединение.
connection_lost_disconnected=Потеряно соединение с сервером расписания. Используйте "Дополнительные действия" -> "Перезагрузить расписание" в верхнем левом углу графического интерфейса.
SChinese=简体中文
TChinese=繁體中文
