

english=English
polish=Polski
Italian=Italiano
French=Français
English=English
Polish=Polski
German=Deutsch
Russian=Русский
Spanish=Español
Czech=Čeština
train_confirm_filter=Підтвердження:
full_date=Повна дата:
train_number_filter=Номер поїзда:
train_train_filter=Поїзд:
clear=Очистити
all=весь
confirmed=підтверджений
incoming=закінчення
departing=запущений
departing_and_incoming=закінчення + початок
activeonly=курсуючі
operating_notes=Примітка
unconfirmed=непідтверджений
train_route_sheduled_arrival=Заплановане прибуття
real_arrival=Фактичне прибуття
train_type=Тип
train_type_full=Класифікація поїзда
train_type_type=Тип поїзда
train_number=Поїзд №
train_number_full=Номер поїзда
from_post=Попередня станція
train_name=Назва поїзда
train_track=Колія
line_number=№ лінії
train_stop_duration=Зупинка
train_route_real_arrival=Фактичне приб.
to_post=До станції
SChinese=简体中文
TChinese=繁體中文
time_enter_modal_error_departure_time_greater_actual=Було записано час відправлення пізніший ніж теперішній час. Якщо ви хочете записати ПРОГНОЗ - спочатку зареєструйте ЗУПИНКУ.
train_description=Опис поїзда
own_notes=Власні коментарі
is_dangerous_cargo=Небезпечний вантаж
operating=K
time_enter_modal_button_train_stop=Зареєструвати зупинку (поїзда)
time_enter_modal_warning_departure_time_greater_actual=Було здійснена спроба записати час, пізніший ніж теперішній час. Ви хочете записати прогноз?
connection_lost_disconnected=Втрачено зв'язок із сервером розкладу. Скористайтеся "Додаткові дії на пості" -> "Перезавантажити розклад" у верхньому лівому кутку екрана.
train_route=Маршрут поїзда
additional_information=Додаткова інформація
from=З
to=До
timetable_type=Тип розкладу
individual=Індивідуальний
yearly=Річний
is_over_gauge_cargo=Перевищення крайнього значення
is_high_risk_cargo=Вантаж з високим рівнем небезпеки
is_overweight_cargo=Надмірна вага вантажу
is_other_exceptional_cargo=Інші виняткові
timetable_head_l=L
timetable_head_peron_track=P T
canceled=N|K
train_route_confirmed=З
train_route_hour=Година
train_route_type=Тип
train_route_station=Станція
train_route_train_stop_calculated_duration=Зупинка
train_route_stop_type=Тип зупинки
train_route_dot=*
# Description
post=Пост:
connection_lost_reconnecting=Втрачено зв'язок із сервером розкладу. Ймовірно, сервер перезавантажується. Спроба повторного підключення.
train_route_sheduled_departure=Заплановане відправлення
sheduled_arrival=Заплановане прибуття
carrier=Перевізник
carrier_shortcut=П
stop_type=Тип зупинки
sheduled_departure=Заплановане відправлення
real_departure=Фактичне відправлення
train_route_real_departure=Фактичне відправлення
star_station=Початкова станція
terminus_station=Кінцева станція
train_list=Перелік поїздів
time_enter_modal_title=Час фактичного відправлення та прибуття поїзда
time_enter_modal_train_add_arrival_minutes_number=Додати до часу прибуття
time_enter_modal_train_add_arrival_minutes_text=Додати до часу прибуття - текст
time_enter_modal_button_rewrite_arrival_time=Скопіювати час прибуття
time_enter_modal_error_departure_time_lower_arrival=Час відправлення не може бути раніше часу прибуття.
time_enter_modal_error_arrival_time_greater_actual=Була спроба вказати час прибуття пізніший за актуальний.
context_menu_enter_arrival_time=Підтвердити час прибуття
time_enter_modal_train_arrived=Поїзд прибув:
train_route_train=Поїзд:
train_route_relation=Напрям:


time_enter_button=Запис часу
time_enter_modal_train_departured=Відправлення поїзда:
time_enter_modal_delay_collision=Зіткнення
time_enter_modal_delay_accident_on_crossing=Аварія на переїзді
time_enter_modal_delay_locomotive_defect=Дефект локомотива
time_enter_modal_train_add_departure_minutes_number=Додати до часу відправлення
time_enter_modal_train_add_departure_minutes_text=Додати до часу відправлення - текст
time_enter_modal_minute_shortcut=хв
time_enter_modal_button_save=Записати
time_enter_modal_button_train_release_stop=Відправити поїзд на зупинці
time_enter_modal_button_cancel=Відмінити
ok=Гаразд
message=Повідомлення
cancel=Скасування
warning=Увага
time_enter_modal_error_departure_time_greater_actual_prognosis=Неможливо скасувати зупинку, поки ще введено ПРОГНОЗ. Будь ласка, вкажіть час відправлення поїзда.
time_enter_modal_save_success=Записано
time_enter_modal_save_failure_no_permission=Година наразі затверджена черговим на наступній станції.
time_enter_modal_delay_network_damage=Пошкодження контактної мережі


context_menu_enter_passing_through_time=Підтвердити час перетину
context_menu_enter_departure_time=Підтвердити час відправлення
time_enter_modal_save_failure_train_too_away=Поїзд занадто далеко, щоб підтвердити дані
time_enter_modal_save_failure_train_not_exist=Поїзд ще не відправився або вже закінчив рух
train_route_line_number=№ лінії
time_enter_modal_save_failure=Виникла помилка
Hungarian=Угорська
