

time_enter_modal_error_departure_time_lower_arrival=发车时间不能早于到达时间。
time_enter_modal_save_failure_no_permission=该车的实际运行时间已由下一站的值班员提交。
# Description
post=车站：
full_date=显示日期：
train_number_filter=车次：
train_confirm_filter=运行状态：
train_train_filter=显示列车：
clear=清除
all=全部
train_description=列车说明
train_route=列车时刻表
additional_information=补充信息
from=始发
to=终到
polish=Polski
english=English
timetable_type=时刻表类型
own_notes=附注
time_enter_modal_train_departured=发车时间：
time_enter_modal_delay_collision=碰撞事故
time_enter_modal_delay_accident_on_crossing=道口事故
time_enter_modal_delay_network_damage=接触网故障
time_enter_modal_delay_locomotive_defect=机破
ok=确认
context_menu_enter_arrival_time=确认到达时间
context_menu_enter_departure_time=确认发车时间
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
French=Français
Czech=Čeština
confirmed=已确认
unconfirmed=未确认
incoming=终到
departing=始发
departing_and_incoming=终到+始发
activeonly=正在运行
operating_notes=操作记录
sheduled_arrival=图定到站时间
train_route_sheduled_arrival=图定到站时间
real_arrival=实际到站时间
train_route_real_arrival=实际到站时间
train_type=类型
train_type_full=列车类型
train_type_type=列车类型
train_number_full=车次
from_post=上一站
train_name=列车名称
to_post=下一站
train_track=股道
line_number=线路号.
train_stop_duration=停车时间
stop_type=停车种类
sheduled_departure=图定发车时间
train_route_sheduled_departure=图定发车时间
real_departure=实际发车时间
train_route_real_departure=实际发车时间
star_station=始发站
terminus_station=终到站
carrier=运营商
carrier_shortcut=运营商
train_list=车站时刻表
individual=临时
yearly=图定
is_over_gauge_cargo=超限货列
is_dangerous_cargo=危险品货列
is_high_risk_cargo=易损品货列
is_overweight_cargo=重载货列
is_other_exceptional_cargo=其余特殊类型
operating=运行
canceled=取消
timetable_head_l=L
timetable_head_peron_track=台|道
train_route_confirmed=过
train_route_hour=时间
train_route_type=类别
train_route_station=车站
train_route_train_stop_calculated_duration=停车时间
train_route_stop_type=停车种类
train_route_dot=*
train_route_train=列车：


time_enter_button=输入时间
time_enter_modal_title=编辑到达和发车时间
time_enter_modal_train_arrived=到达时间：
time_enter_modal_train_add_arrival_minutes_number=到达时间加时
time_enter_modal_train_add_arrival_minutes_text=到达时间加时原因
time_enter_modal_train_add_departure_minutes_number=发车时间加时
time_enter_modal_train_add_departure_minutes_text=发车时间加时原因
time_enter_modal_minute_shortcut=分
time_enter_modal_button_train_stop=进入扣停 (同步计划发车时间)
time_enter_modal_button_train_release_stop=解除扣停 (取消同步发车时间)
time_enter_modal_button_save=保存
time_enter_modal_button_cancel=取消
time_enter_modal_button_rewrite_arrival_time=从到达时间复制
message=消息
cancel=取消
warning=警告
time_enter_modal_error_arrival_time_greater_actual=不能填写比当前时间更晚的到达时间。
time_enter_modal_error_departure_time_greater_actual=填写的出发时间比当前时间更晚。如果是想向下一站给出预计发车时间，请考虑将列车设为扣停状态。
time_enter_modal_warning_departure_time_greater_actual=填写的出发时间比当前时间更晚。填写的是列车预计发车时间吗？
time_enter_modal_error_departure_time_greater_actual_prognosis=不能在填写预计发车时间的情况下取消列车扣停。请填写列车发车时间。
time_enter_modal_save_success=已保存
time_enter_modal_save_failure=发生错误


context_menu_enter_passing_through_time=确认通过时间
train_number=车次
train_route_line_number=线路号
train_route_relation=关联线路：
time_enter_modal_save_failure_train_too_away=列车太远，无法确认数据
time_enter_modal_save_failure_train_not_exist=列车尚未出发或者已经终到
connection_lost_reconnecting=失去与EDR服务器的连接。服务器可能正在重启。正在尝试重新连接。
connection_lost_disconnected=失去与EDR服务器的连接。退出本界面，然后使用左上角“其它车站命令”菜单中的“刷新时刻表”来重新连接。
SChinese=简体中文
TChinese=繁體中文
