

time_enter_modal_error_departure_time_lower_arrival=發車時間不得早於到達時間。
time_enter_modal_save_failure_no_permission=此時間目前已由下一站的行車值班員確認。
# Description
post=號誌站：
full_date=完整日期：
train_number_filter=列車車次：
train_confirm_filter=確認狀態：
train_train_filter=列車：
clear=清除
all=全部
train_description=列車說明
train_route=列車運轉路線
additional_information=其他資訊
from=從
to=至
polish=Polski
english=English
timetable_type=時刻表類型
own_notes=自訂註記
time_enter_modal_train_departured=列車發車：
time_enter_modal_delay_collision=碰撞
time_enter_modal_delay_accident_on_crossing=平交道事故
time_enter_modal_delay_network_damage=電車線設備損壞
time_enter_modal_delay_locomotive_defect=機車故障
ok=確定
context_menu_enter_arrival_time=確認到達時間
context_menu_enter_departure_time=確認發車時間
English=English
Polish=Polski
German=Deutsch
Italian=Italiano
Russian=Русский
Hungarian=Magyar
Spanish=Español
French=Français
Czech=Čeština
confirmed=已確認
unconfirmed=未確認
incoming=終到
departing=始發
departing_and_incoming=始發＋終到
activeonly=運轉中
operating_notes=運轉註記
sheduled_arrival=表定到達
train_route_sheduled_arrival=表定到達
real_arrival=實際到達
train_route_real_arrival=實際到達
train_type=車種
train_type_full=列車種類
train_type_type=列車種類
train_number_full=列車車次
from_post=來自號誌站
train_name=列車名稱
to_post=前往號誌站
train_track=股道
line_number=路線編號
train_stop_duration=停車時間
stop_type=停車類型
sheduled_departure=表定發車
train_route_sheduled_departure=表定發車
real_departure=實際發車
train_route_real_departure=實際發車
star_station=始發站
terminus_station=終到站
carrier=營運業者
carrier_shortcut=營運業者
train_list=列車一覽
individual=臨時
yearly=定期
is_over_gauge_cargo=超限貨物
is_dangerous_cargo=危險貨物
is_high_risk_cargo=高風險貨物
is_overweight_cargo=超重貨物
is_other_exceptional_cargo=其他特殊貨物
operating=運轉（K）
canceled=取消（N|K）
timetable_head_l=路線（L）
timetable_head_peron_track=月台／股道（P／T）
train_route_confirmed=已確認（Z）
train_route_hour=時間
train_route_type=種類
train_route_station=車站
train_route_train_stop_calculated_duration=計算停時
train_route_stop_type=停車類型
train_route_dot=*
train_route_train=列車：


time_enter_button=輸入時間
time_enter_modal_title=列車實際到達及發車時間
time_enter_modal_train_arrived=列車到達：
time_enter_modal_train_add_arrival_minutes_number=到達時間加時（分鐘）
time_enter_modal_train_add_arrival_minutes_text=到達加時原因
time_enter_modal_train_add_departure_minutes_number=發車時間加時（分鐘）
time_enter_modal_train_add_departure_minutes_text=發車加時原因
time_enter_modal_minute_shortcut=分
time_enter_modal_button_train_stop=登錄運轉停車（同步表定發車時間）
time_enter_modal_button_train_release_stop=取消運轉停車（取消同步發車時間）
time_enter_modal_button_save=儲存
time_enter_modal_button_cancel=取消
time_enter_modal_button_rewrite_arrival_time=將到達時間複製為發車時間
message=訊息
cancel=取消
warning=警告
time_enter_modal_error_arrival_time_greater_actual=輸入的到達時間晚於目前時間。
time_enter_modal_error_departure_time_greater_actual=輸入的發車時間晚於目前時間。若要輸入預計發車時間，請先登錄運轉停車。
time_enter_modal_warning_departure_time_greater_actual=輸入的時間晚於目前時間。要將其設為預計發車時間嗎？
time_enter_modal_error_departure_time_greater_actual_prognosis=已設定預計發車時間時無法取消運轉停車。請先輸入列車的實際發車時間。
time_enter_modal_save_success=已儲存
time_enter_modal_save_failure=發生錯誤


context_menu_enter_passing_through_time=確認通過時間
train_number=車次
train_route_line_number=路線編號
train_route_relation=運轉區間：
time_enter_modal_save_failure_train_too_away=列車距離過遠，無法確認資料
time_enter_modal_save_failure_train_not_exist=列車尚未開始運轉，或已結束運轉
connection_lost_reconnecting=與時刻表伺服器的連線已中斷。伺服器可能正在重新啟動，正在嘗試重新連線。
connection_lost_disconnected=與時刻表伺服器的連線已中斷。請使用畫面左上角的「號誌站其他操作」->「重新載入時刻表」。
SChinese=简体中文
TChinese=繁體中文
