

# {0} train number. {1} time {2} track
Lineblock_Lock=鎖閉起始閉塞！
Train_Question=哪一列車已開出？
Train_Arrived={0}次列車已於{1}到達。
Train_Departed={0}次列車已於{1}開出。
Train_Request=請問是否可接收{0}次列車？
Train_Request_With_Track=請問是否可經第{2}線接收{0}次列車？
Train_Permission=同意於{1}接收{0}次列車。
Train_Permission_With_Track=同意於{1}經第{2}線接收{0}次列車。
Train_Cancelled={0}次列車已取消開行。

#{0} numer pociągu. {1} numer toru
Entrance_Given={0}次列車進站進路已開通至第{1}股道。
#{0} numer pociągu. {1} stacja docelowa
EntranceExit_Given={0}次列車往{1}站的通過進路已開通。

#{0} powtarzana wiadomość
Repeat=我復誦如下：{0}

#odrzucenia
#{0} numer pociągu. {1} numer toru. {2} powod
Train_Denial_Template={0}次列車無法接車，原因：{2}（第{1}線）
Train_Denial_Train_Doesnt_Exist={0}次列車無法接車，因為沒有這班列車。
Train_Denial_Track_Occupied={0}次列車無法接車，因為股道已占用。
Train_Denial_Track_Is_Closed={0}次列車無法接車，因為股道已封鎖。
Train_Denial_I_Have_Higher_Priority={0}次列車無法接車，本站須先開出優先等級較高的列車。
Train_Denial_No_Track_Available={0}次列車無法接車，因為站內沒有空股道。
Train_Denial_Train_Doesnt_Exist_With_Track={0}次列車無法經第{1}線接車，因為沒有這班列車。
Train_Denial_Track_Is_Closed_With_Track={0}次列車無法經第{1}線接車，因為該線已封鎖。
Train_Denial_Track_Occupied_With_Track={0}次列車無法經第{1}線接車，因為該線已占用。
Train_Denial_No_Track_Available_With_Track={0}次列車無法經第{1}線接車，因為站內沒有空股道。
Train_Denial_I_Have_Higher_Priority_With_Track={0}次列車無法經第{1}線接車，本站須先開出優先等級較高的列車。

#UI
Button_Send=傳送
PresetInput_Train=輸入車次
PresetInput_Time=輸入時間
PresetInput_Reason=選擇拒絕原因
PresetInput_Track=選擇線別（選填）
Train_Denial_None=無
PresetSelector_or=或
PresetSelector_use_chat_window=使用聊天視窗
ChooseCommunactionMethod_Header=選擇通訊方式
Train_Departed_With_Track={0}次列車已於{1}經第{2}線開出。
Train_Denial_I_Have_Permission={0}次列車無法接車，本站已取得發車許可。
Train_Denial_I_Have_To_Ask_Further={0}次列車目前無法接車，我必須先向下一站請求同意。
Train_Denial_This_Would_Block_My_Station={0}次列車無法接車，否則會造成本站行車僵局。
Train_Denial_This_Would_Block_My_Station_With_Track={0}次列車無法經第{1}線接車，否則會造成本站行車僵局。
Train_Denial_I_Have_Permission_With_Track={0}次列車無法經第{1}線接車，本站已取得發車許可。
Train_Denial_I_Have_To_Ask_Further_With_Track={0}次列車目前無法經第{1}線接車，我必須先向下一站請求同意。
Train_Denial_Unknown_Line={0}次列車無法接車，因為路線不明。
Train_Denial_Unknown_Line_With_Track={0}次列車無法經第{1}線接車，因為該線不明。
Currently=目前
Message_to_player=您收到一則管理員訊息。若要回覆，請在下一則訊息前加上 /a。
Block_message=傳送檢舉的功能已暫時停用
Train_Removed_Semaphore_Turned_Off=列車 {0} 已被移除。從號誌機 {1} 為該列車設定的進路已自動解鎖。
voice_chat_block=您已被禁止使用語音聊天
neighbour_blocked=相鄰車站的玩家已被禁止通話
chat_blocked=您已被暫時禁止在聊天中發言
Train_Arrived_Without_Time={0}次列車已到達。
Train_Permission_Without_Time=同意接收{0}次列車。
Train_Permission_With_Track_Without_Time=同意經第{2}線接收{0}次列車。
Train_Departed_Without_Time={0}次列車已開出。
Train_Departed_With_Track_Without_Time={0}次列車已經由第{2}線開出。
rapports_blocked_with_reason=傳送檢舉的功能已停用。解除日期：{0}。原因：{1}
chat_blocked_with_reason=您已被禁止在聊天中發言。解除日期：{0}。原因：{1}
voice_chat_blocked_with_reason=您已被禁止使用語音聊天。解除日期：{0}。原因：{1}
