

JunctionButton=Váltóállítás
TrainRouteButton=Főjelző gomb
ShuntingRouteButton=Tolatásjelző gomb
ReleaseTrainRouteButton=Vonatvágányút kényszeroldás
ReleaseShuntRouteButton=Tolatóvágányút kényszeroldás
SubstituteSignalButton=Hívójelzés
LineBlockPZKButton=Menetirány elfogadás
LineBlockWBLButton=Menetirány kérés
LineBlockZWBLButton=Menetirány feloldás
DominoPanelTrainsList=Vonatok ezen a pályaszakaszon:
OrderRevokeSubsidiarySignal=Hívójelzés visszavonása
OrderShuntingRoute=Tolatóvágányút beállítása
OrderTrainRoute=Vonatvágányút beállítása
OrderAxleCounterResetConfirm=Tengelyszámláló alaphelyzetbe állító
OrderForceReleaseTrainRoute=Vonatvágányút oldása
OrderForceReleaseShuntingRoute=Tolatóvágányút oldása
OrderReleaseShuntRoute=Tolatóvágányút oldása
OrderSubsidiarySignalConfirm=Hívójelzés kivezérlése
LineBlockAZKButton=Menetirány kényszerváltás
OrderPlus=Váltó egyenes irányba
OrderMinus=Váltó kitérő irányba
OrderAZKP=Kényszerített irányváltás
OrderNONP=Helytelen irányú közlekedés engedélyezése
OrderRevokeNONP=Helytelen irányú közlekedés leállítása
AxleCounterResetButton=Tengelyszámláló visszaállítása
OccupancySkippingButton=Vágány foglaltság felülírása
LineBlockDPOButton=Kényszerített vonatindítás
LineBlockDKOButton=Kényszerített vonatfogadás
OrderPO=Menetirány kérése
OrderKO=Visszajelentés adása
OrderDPOP=Kényszerített vonatindítás előkészítése
OrderDKOP=Kényszerített vonatfogadás előkészítése
OrderStop=Fővágány lezárása
OrderZWBL=Menetirány feloldása
OrderOWBL=Kérelem törlése
LineBlockSTOPButton=Fővágány lezárása
LineBlockNPButton=Helytelen vágány érkezés
LineBlockNOButton=Helytelen vágány indulás
OrderStopSignal=Jelző megállj!
OrderPZK=Menetirányváltás elfogadása
OrderWBL=Menetirány kérés
BrokenSwitchRemoverButton=Váltófelvágás helyreállítás
OrderRemoveBrokenAlertConfirm=Váltófelvágás helyreállítása
LineBlockPOButton=Menetiránykérés
LineBlockKOButton=Megérkezés igazolása
OrderSkippingInsulatedCircuitInit=A használata megengedi, hogy egy pályaszakasz foglaltságát felülírd
OrderOpenCrossing=Sorompó nyitása
OrderCloseCrossing=Sorompó zárása
OrderReleaseCrossingConfirmation=Az útvonal megerősítésének visszavonása
RoadCrossingClose=Sorompó zárása gomb
RoadCrossingRevokeConfirmation=Útkereszteződés – visszavonja a visszaigazolást az útvonalon
RoadCrossingOpenButton=Útátjáró nyitógomb
RoadCrossingCloseButton=Útátjáró zárógomb
RoadCrossingRevokeConfirmationButton=Útkereszteződés – visszavonja a visszaigazolást az útvonalon
RoadCrossingMultiButtonButton=Útátjáró gomb
DayButtonButton=Tompított mód
NightButtonButton=Fényszóró mód
Dispatcher_Assistant_Use_KO_Block=The train arrived the station. Please use the KO button in domino panel!
Options_EDRTime_AutoSend=EDR idők automatikus kitöltése
Dispatcher_Assistant_Use_PO_Block=The train left the station. Please use the PO button in domino panel!
