

ReleaseShuntRouteButton=調車進路解鎖按鈕
TrainRouteButton=列車號誌機按鈕
ShuntingRouteButton=調車號誌機按鈕
SubstituteSignalButton=代用號誌按鈕
LineBlockWBLButton=啟用站間閉塞／選擇方向按鈕
LineBlockPZKButton=變更方向按鈕
LineBlockZWBLButton=解除站間閉塞按鈕
LineBlockSTOPButton=封鎖站間軌道按鈕
LineBlockAZKButton=緊急變更方向按鈕
LineBlockKOButton=終端閉塞按鈕
LineBlockNOButton=反向路線發車按鈕
LineBlockNPButton=自反向路線進站按鈕
LineBlockDPOButton=臨時鎖閉起始閉塞按鈕
LineBlockDKOButton=臨時鎖閉終端閉塞按鈕
LineBlockPOButton=起始閉塞按鈕
OccupancySkippingButton=略過占用狀態按鈕
AxleCounterResetButton=計軸器歸零按鈕
OrderMinus=扳至反位
OrderStopSignal=撤銷允許號誌
OrderAxleCounterResetConfirm=計軸器歸零
OrderForceReleaseTrainRoute=解鎖列車進路
OrderForceReleaseShuntingRoute=解鎖調車進路
OrderReleaseShuntRoute=解鎖調車進路
OrderSubsidiarySignalConfirm=顯示代用號誌
OrderRemoveBrokenAlertConfirm=清除轉轍器擠岔警示
OrderOWBL=撤銷啟用站間閉塞／同意請求
OrderPZK=同意啟用閉塞／設定方向
OrderZWBL=解除站間閉塞
OrderNONP=接入反向路線來車／向反向路線發車
OrderPO=鎖閉起始閉塞
OrderKO=鎖閉終端閉塞
OrderDPOP=臨時鎖閉起始閉塞
OrderDKOP=臨時鎖閉終端閉塞
OrderStop=封鎖站間軌道
OrderTrainRoute=設定列車進路
OrderShuntingRoute=設定調車進路
DominoPanelTrainsList=此股道上的列車：
OrderRevokeSubsidiarySignal=撤銷代用號誌
OrderSkippingInsulatedCircuitInit=按住按鈕，以略過軌道電路占用狀態
JunctionButton=轉轍器／脫軌器位置切換按鈕
ReleaseTrainRouteButton=列車進路解鎖按鈕
BrokenSwitchRemoverButton=清除轉轍器擠岔警示按鈕
OrderPlus=扳至定位
OrderWBL=啟用站間閉塞／請求同意
OrderAZKP=緊急變更站間閉塞方向
OrderRevokeNONP=撤銷反向路線行車
RoadCrossingClose=關閉遮斷機按鈕
OrderOpenCrossing=開啟遮斷機
OrderCloseCrossing=關閉遮斷機
OrderReleaseCrossingConfirmation=撤銷平交道在進路中的鎖閉
RoadCrossingRevokeConfirmation=撤銷平交道鎖閉狀態按鈕
RoadCrossingOpenButton=開啟遮斷機按鈕
RoadCrossingCloseButton=關閉遮斷機按鈕
RoadCrossingRevokeConfirmationButton=撤銷平交道鎖閉狀態按鈕
RoadCrossingMultiButtonButton=遮斷機控制按鈕
NightButtonButton=全亮模式
DayButtonButton=減光模式
Dispatcher_Assistant_Use_KO_Block=列車已到達車站。請使用 EP 盤上的 KO 按鈕！
Options_EDRTime_AutoSend=自動填寫 EDR
Dispatcher_Assistant_Use_PO_Block=列車已離開車站。請使用 EP 盤上的 PO 按鈕！
Seal_Remove=拆除鉛封
OWBLReminder_PreKick=前一站已撤銷下列站間閉塞，請在約 {0} 秒內一併撤銷：{1}，否則將被踢出伺服器！
AutomaticPOBlockHandler_PreKick=請在約 {0} 秒內使用 PO 按鈕處理下列起始閉塞：{1}，否則將被踢出伺服器！
AutomaticKOBlockHandler_PreKick=請在約 {0} 秒內使用 KO 按鈕處理下列終端閉塞：{1}，否則將被踢出伺服器！
LinearBlockadeReminder_PreKick=請在約 {0} 秒內接受下列站間閉塞請求：{1}，否則將被踢出伺服器！
RouteClearReminder_PreKick=請在約 {0} 秒內回覆下列車次的路線是否淨空：{1}，否則將被踢出伺服器！
OWBL_Reminder_Send_Message=相鄰車站已撤銷下列站間閉塞：{0}。請在本站一併撤銷。
Linear_Blockade_Reminder_Unblock=下列站間閉塞請求尚待處理：{0}。請儘速處理。
Route_Clear_Reminder_Send_Message=下列列車正在等待路線是否淨空的回覆：{0}
EDR_Force_Enable_Auto_Inputs=由於未填寫 EDR 紀錄，已啟用 EDR 自動填寫功能。
EDR_Inputs_Check_Reminder=請記得在 EDR 填寫列車到達及發車時間。
Auto_PO_Block_Gentle_PreKick=請記得使用 EP 盤上的 PO 按鈕處理下列閉塞：{0}。
Auto_KO_Block_Gentle_PreKick=請記得使用 EP 盤上的 KO 按鈕處理下列閉塞：{0}。
Route_Clear_Reminder_Gentle_PreKick=請記得回覆下列列車的路線是否淨空：{0}。
Line_Lock_Reminder_Gentle_PreKick=請記得接受下列站間閉塞請求：{0}。
OWBL_Reminder_Gentle_Prekick=下列站間閉塞已由相鄰車站撤銷，請記得在本站一併撤銷：{0}。
